### ISSUE TITLE
line.connectNull causes stacked charts to break

### ISSUE THREAD

**Issue by neil-morrison44** [naver/billboard.js#10]
## Description
Stacked charts have gaps in them when there's null values, line.connectNull prevents gaps in line charts.
However connectNull works poorly with stacked charts, with the stacks overlaying each other completely.

## Steps to check or reproduce
When connectNull is true:
https://jsfiddle.net/jL196Lnv/1/
Stacks overlay each other completely

When connectNull is false:
https://jsfiddle.net/7x42jqtr/1/
Gaps in filled in area

**Comment by netil** [comment]
thanks, @neil-morrison44 for the report.
When `connectNull` is true, the area isn't rendered properly as when is false.

Try fix for the next release.

![image](https://user-images.githubusercontent.com/2178435/27078123-6ea88d82-506d-11e7-9e95-3f51c6f44f03.png)

BTW, when you set same data types for all data binding, you can use [data.type](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.data:type), instead of setting all the type one by one.

```js
  data: {
    "types": {
      dynamodb_table: "area",
      database_server: "area",
      elasticache_node:"area"
     }
  },

  // can be written as
  data: {
    "type": "area"
  },
```
