### ISSUE TITLE
Rendering while hidden causes legend items to overlap

### ISSUE THREAD

**Issue by cristinecula** [naver/billboard.js#1015]
## Description
I'm rendering the chart in a hidden container and when I make the container visible, the chart is not rendered properly. This is expected, as the container does not have proper dimensions when it is hidden, so I call `chart.resize()`. However, this results in a chart with overlapping legend labels and other rendering issues:

![2019-08-07-102906_639x346_scrot](https://user-images.githubusercontent.com/710155/62603255-344a4f80-b8fe-11e9-91d2-55fa8c8b3065.png)

Further resizing of the window does not fix the rendering.

## Steps to check or reproduce
https://jsbin.com/fajizo/edit?html,output

**Comment by netil** [comment]
Hi @cristinecula, basically the issue is attached to the `off-screen` rendering.
If you try render(initialize) on non visible element, will likely face same issue across whole chart elements rendering.

Is because positioning each chart elements, need to be calculated based on the dimension of that element. But if isn't visible, there's no proper way to get exact dimension.

One simple approach to solve that I'm thinking is:
- Check the visibility of the chart element
  -  If the element isn't visible, generate the instance, but hold the rendering process marking internally that the rendering wasn't finished.
  - When element becomes visible, re-starts the rendering process where it was stopped.

Any feedback will be appreciated.

**Comment by cristinecula** [comment]
@netil Thank you for looking into this issue!

Checking for visibility is easy using https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent, but knowing when the element becomes visible is hard.

I do not think this visibility check should be handled by billboard.js, instead I would prefer calling a method when the chart is made visible by my app. 

My main issue is with the fact that calling `chart.resize()` when the element is visible does not fix the rendering. A possible solution would be adding a new method that recalculates the positioning of the elements, as if the chart was just constructed.

**Comment by netil** [comment]
[MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) can be used to look the visibility, but in this case need to drop the support on old IEs for this feature.

So, the possible approach in this will be:
- When chart bind element visibility is hidden, then try not fully goes to the generation(render) process.
- When bind element is visible and `redraw` happens(explicitly called by API or resize, etc.), continues the initial rendering process.

**Comment by cristinecula** [comment]
@netil I managed to force a complete resize by clearing the internal dimensions cache:

```
chart.resize() // this makes the chart visible
chart.internal.clearLegendItemTextBoxCache(); // clears the cached dimensions
chart.internal.resetCache();
chart.resize(); // this fixes the rendering
```

https://jsbin.com/voqawayeha/2/edit?html,output

**Comment by netil** [comment]
@cristinecula, implemented new **render** option.
- https://github.com/naver/billboard.js/blob/master/src/config/Options.js#L3384

Try with the nightly for the test.
- https://github.com/naver/billboard.js#nightly-version

**Comment by netil** [comment]
seems to have side-effect. Revert the merge

**Comment by cristinecula** [comment]
Woah... That's amazing! :+1: 
Thank you!
