### ISSUE TITLE
Distributing as an ES module

### ISSUE THREAD

**Issue by stof** [naver/billboard.js#1080]
Currently, the code is built as an UMD build only with webpack.
This has an unfortunate effect that each d3 component is imported fully, even though the source code does not do it (for instance, only the linear scale is used from `d3-scale`, which is a very small part of the package). This does not allow webpack to perform powerful tree-shaking (and d3 packages are in the process of being marked as free of side-effects for most of them, precisely to help with that).
Webpack also performs module concatenation optimizations (which help with minification and dead code elimination) only for ES modules.

So it would be great to provide an ESM build of billboard. Webpack is not able to do it yet (this is a feature planned for webpack 5), but rollup can do it (and can even output both ESM and UMD very easily).

**Comment by netil** [comment]
Hi @stof, thanks for the suggestion.

Switching one to another can be easy or not. Because the "switch" means leaving(or stopping) the use of webpack, which basically I don't want to for several reasons.
- will eliminate all the "stabilized" build configuration and start again.
- likely or not `webpack` is the most popular bundler, which means a lot of users & communities behind.
  > variety of toolchains, docs, make more easier for the future contribution, etc.

But, don't get misunderstood on this. Just considering the final result, is reasonable the switching.

As you mentioned, webpack v5 will have ESM target functionality and according their past release schedule experience, I'm seeing these will happen soon.
- https://github.com/webpack/changelog-v5/blob/master/README.md#runtime-modules

So, I'll be looking the webpack v5, but aside of this, I'll look for any best solution for this.

Feel free on commenting any new ideas or whatever.

**Comment by stof** [comment]
Another possibility if the source code does not use non-standard ES features is to make `module` point to `src/core.js`, and document that people wanting to target older browsers will need to include billboard.js in the scope of what they transpile (or force the loading of the CommonJS bundle).
Note that given the dependencies include d3-array 2.x and d3-scale 3.x, there is already such a new (new major versions of d3 packages are now shipped as ES6 code).

I'm currently using that approach in my project, by defining a resolve alias in my webpack config (so that I can keep my source code using `import { bb } from 'billboard.js'` and it works fine.

However, doing such change would be a BC break for existing projects using webpack or rollup (or whatever other bundle preferring to use `module` over `main`) and excluding `node_modules` from their transpiler config (many projects do this for performance reason, due to the old convention of always shipping ES3 code in packages).

**Comment by stof** [comment]
With v2 being written in typescript, please take this request into account, as importing `src/` won't work anymore to use ES modules.

**Comment by netil** [comment]
@stof, I'm testing the `esm` build using rollup.js.
Would you like to try the build?
- https://github.com/naver/billboard.js/blob/v2/dist/billboard.esm.js

```sh
npm install git+https://github.com/naver/billboard.js.git#v2 --save
```

**Comment by netil** [comment]
At this point, the package provides UMD (`/dist`) and ESM(`dist-esm`) modules, which solves the issue.
- https://unpkg.com/browse/billboard.js/
