### ISSUE TITLE
Billboard.js 1.11.0 doesn't support IE 11

### ISSUE THREAD

**Issue by imbyungjun** [naver/billboard.js#1145]
## Description

Billboard.js v1.11.0 doesn't work in IE. 
I think that it's because It depends on d3-array 2.4.0 that doesn't support IE anymore. https://github.com/d3/d3-array/issues/87

https://github.com/naver/billboard.js/blob/fbb89464ff78a427c9b9f5449d628bd269784e0e/package.json#L110

**Comment by netil** [comment]
Hi @imbyungjun, I ran the build and seems working fine.
The `d3-array` used in `Stanford Diagram` plugin only and from the base library it was removed the use of it(#710).

![ie11](https://user-images.githubusercontent.com/2178435/69857878-274dd380-12d4-11ea-81ad-8b83e3e19019.gif)

Could you provide detailed reproducible case?

**Comment by netil** [comment]
@imbyungjun, from the `1.11.0` release, the `d3` dependency is updated to be as separated used d3 modules only. (Ref. #1054)

From this change, when you import billboard.js, the dependent d3 modules will be concatenated & bundled in your build from the `node_modules`.

If you use `webpack` as bundler, generally `node_modules` is pointed to be excluded from the loader boundary, where this issue comes.

This issue will not have effect if you include as `<script>` tag. Only is happening when you import as ESM and is targeting for old IEs.

So, there're two possible solution on this.

## 1) Make 'd3-*' modules to be transpiled

When your bundler(ex. webpack) configuration set is excluding `node_modules`, so update to target `d3-` modules giving below configuration.

- https://webpack.js.org/configuration/module/#condition

```js
// webpack.config.js
module: {
	rules: [
		{
			test: /(\.js)$/,
			exclude: {
				test: /node_modules/,
				not: [/(d3\-.*)$/]
			},
			use: {
				loader: "babel-loader"
			},
		},
```

### Pros
You can apply your own optimized configuration for dependent modules.

### Cons
You might need to handle all of possible legacy related polyfills and transformation needed.

## 2) Use transpiled d3 packaged build

If you don't want to handle all possible configuration for legacy browsers, just use packaged build.

```js
import {bb} from "billboard.js/dist/billboard.pkgd";

bb.generate(...);
```

In this case, you need to add on your bundler configuration to not concatenate `d3` modules, because packaged build already contains them.

```js
// webpack.config.
externals: /^(d3\-.*)$/i,
```
- https://webpack.js.org/configuration/externals/

### Pros
Get rid all the headache configuration for the legacy environment.

### Cons
Might possibly make bigger the build size, because of polyfills.

**Comment by imbyungjun** [comment]
Appreciate for your detailed guide! It perfectly works for me.

I fixed it by **transpiling d3-\* modules**.

> To resolve d3-scale module's compatibility issue, "@babel/plugin-transform-for-of" plugin was needed

**Comment by jm-chong** [comment]
If you are using babel7 and `/node_modues/` still not transplie to es5, consider this solution.
- https://github.com/webpack/webpack/issues/2031#issuecomment-479451346
- https://babeljs.io/docs/en/configuration#whats-your-use-case

**Comment by netil** [comment]
FYI @jm-chong, @imbyungjun
Downgraded `d3-scale` version to get rid the need of transpile the code.
- https://github.com/naver/billboard.js/releases/tag/1.12.3
