### ISSUE TITLE
Area chart is not stretching out to bottom if axis.y.min < 0

### ISSUE THREAD

**Issue by qkreltms** [naver/billboard.js#1188]
## Description
Area chart is not stretching out to bottom if set axis.y.min = -1.
![fdfdfdfdf](https://user-images.githubusercontent.com/25196026/71607127-2ac9c880-2bba-11ea-85b8-d868e41d9196.png)

## Steps to check or reproduce
Check out [this](https://codepen.io/qkreltms/pen/KKwXNPV)

I solved this issue by setting axis.y.padding = 0

**Comment by netil** [comment]
Hi @qkreltms, is functioning as expected. If area covers to the minus numbers, is a mal-representation of the data. Because positive data are based from the 0.

In a case of minus data, is will be represented as:
![image](https://user-images.githubusercontent.com/2178435/71653961-7b842180-2d72-11ea-9e62-de91b83c5e95.png)
