### ISSUE TITLE
Latest billboard.js 1.11.1 is not available on cdnjs.cloudflare.com

### ISSUE THREAD

**Issue by inferno-chromium** [naver/billboard.js#1190]
## Description
https://cdnjs.com/libraries/billboard.js does not have latest released version 1.11.1. Its latest is the old version 1.10.2.

## Steps to check or reproduce
https://cdnjs.cloudflare.com/ajax/libs/billboard.js/1.11.1/billboard.min.js results in not found.

**Comment by netil** [comment]
Hi @inferno-chromium, the new release was automatically distributed to cndjs, but since `1.11.0` release was stopped updating. I'll be figuring out the cause.
Meanwhile, try using alternative CDNs like `jsDelivr` or `unpkg`.

- jsDelivr: https://cdn.jsdelivr.net/npm/billboard.js/
- unpkg: https://unpkg.com/billboard.js/

You can point the latest version by :
- https://cdn.jsdelivr.net/npm/billboard.js/dist/billboard.min.js
- https://unpkg.com/billboard.js/dist/billboard.min.js

**Comment by netil** [comment]
Ref. https://github.com/cdnjs/cdnjs/issues/13661

**Comment by netil** [comment]
@inferno-chromium, added new version to cdnjs
- https://cdnjs.com/libraries/billboard.js/1.11.1
