### ISSUE TITLE
How to point (not select) a certain datum?

### ISSUE THREAD

**Issue by softage0** [naver/billboard.js#1212]
## Description
Even if `selection.enabled: false`, data can be pointed like the below:
<img width="323" alt="Screen Shot 2020-01-20 at 2 06 29 PM" src="https://user-images.githubusercontent.com/7719707/72700115-3cd1d200-3b8e-11ea-9c1a-cd42c5127e44.png">

Is there any way to **point**(not select) a certain datum with billboard.js API?

**Comment by netil** [comment]
Hi @softage0, when `data.selection.enabled=true`, it means you can select data point as below screenshot.
![data-selection](https://user-images.githubusercontent.com/2178435/72766562-cd162280-3c33-11ea-9294-90bb6212b2a6.gif)

I can't get clearly what is your needs. Can you specify more in detail?

**Comment by softage0** [comment]
<img width="323" alt="Screen Shot 2020-01-20 at 2 06 29 PM" src="https://user-images.githubusercontent.com/7719707/72767437-29c70c80-3c37-11ea-92d4-ff91d1edd62c.png">

Even if `selection.enbled: false`, the above click action works.
I want to fire this `click` action with billboard.js API or JS. Not with mouse or touch.
It there any way to do this?

**Comment by netil** [comment]
The selection shouldn't be working when `data.selection.enable=false` is set. I'm not reproducing the selection on that circumstances. If happens on your case, please provide a reproducible full generation code.

And when you want select data points by API, you can use [`.select()`](https://naver.github.io/billboard.js/release/latest/doc/Chart.html#select) API. Checkout the API doc & its examples.

**Comment by softage0** [comment]
![bill_test](https://user-images.githubusercontent.com/7719707/72775615-71a75d00-3c52-11ea-8eb9-35b42af43a49.gif)

It actually doesn't look like `selection`.
I used almost nothing but default options. the code I used the below:
```js
import 'billboard.js/dist/theme/insight.css';

...

        this.chart = bb.generate({
            data: {
                x: 'x',
                columns: [
                    ["x", "2020-01-13", "2020-01-14", "2020-01-15", "2020-01-16", "2020-01-17", "2020-01-18", "2020-01-19", "2020-01-20"],
                    ["조회수", 52260, 66284, 39357, 59874, 38758, 33284, 33103, 57717],
                ],
            },
            axis: {
                x: {
                    type: 'timeseries',
                    tick: {
                        format: '%d일',
                    },
                },
            },
            tooltip: {
                format: {
                    value: (v) => formatNumber(v),
                },
            },
            bindto: `#${this.chartElementId}`,
            size: {
                height: 177,
            },
        });
```

My billboard.js version in `package.json`:
```json
    "billboard.js": "^1.11.1",
```

It used with `React`.

**Comment by netil** [comment]
@softage0, IMO you misunderstood the meaning of "selection".

The normal interaction behaves as:
- For **mouse** supported environment: 
  When users `mouseover` on data point, it will expand data point & show tooltip
- For **touch** supported environment:
  When users `touch` on data point, it will expand data point & show tooltip.

If you want to make to not interact based on users' event, you can use [`interaction.enabled=false`](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.interaction) option, but in that case will not be able to make data points to expand nor tooltip show, because they're enabled when `interaction.enable=true` case.

One possible workaround on this is,

- Set chart element to not receive users' event by setting
```css
.bb-event-rects {
    pointer-events: none;
}
```
- And use [`.tooltip.show()`]() API to show tooltip
```js
// it will show tooltip & expand data point where x Axis value is '2020-01-15'
chart.tooltip.show({x: new Date("2020-01-15 00:00:00")});
```

Try calling `.tooltip.show(https://naver.github.io/billboard.js/release/latest/doc/Chart.html#tooltip%25E2%2580%25A4show)` from the console from the below example
- https://codesandbox.io/s/hopeful-leftpad-2hzhh

**Comment by softage0** [comment]
Oh, I didn't know it works a different way depends on environments.
I used it in the mobile-emulated environment so I didn't know it works that way.

Thanks for your advice and I solved the issue with `.tooltip.show()` API.
