### ISSUE TITLE
Inconsisten left padding (with data vs without data)

### ISSUE THREAD

**Issue by LeonardAB** [naver/billboard.js#1251]
## Description
When creating a graph bar, I found that the left padding (distance between the Y axis with the graph's container border) to be inconsistent between when there is data and no data.
When there is no data, the padding becomes a lot smaller. 

## Steps to check or reproduce
https://jsfiddle.net/pg1yq2fh/3/ 

with data:
![image](https://user-images.githubusercontent.com/14308605/75208423-f0963500-57be-11ea-8c6a-4e9bc4db1b67.png)

without data (in the JS, comment/uncomment the relevant dataset). This happens even when tick values are added manually.
![image](https://user-images.githubusercontent.com/14308605/75208469-20ddd380-57bf-11ea-90e0-b6d908a6af19.png)

**Comment by netil** [comment]
Hi @LeonardAB, this is the result of y Axis options - `padding`, `tick.values` and `tick.count` collision.

- `tick.count` option, the y Axis value will be determined in a range of the current y domain value.
- `tick.values` option, the y Axis tick values will be determined as the given values based on the current y Axis domain value.

So, setting both `tick.count` and `tick.values` options together will likely have some inconsistency to determine "final"  tick values.

```js
y: {
    tick: {
        values: yTicks, // without 'tick.count' option, will display as the right screenshot
        count : 5 // without 'tick.values' option, will display as the left screenshot
    }
}
```

![image](https://user-images.githubusercontent.com/2178435/75506762-5fbf9380-5a22-11ea-9c80-30865c55b5d4.png)

But the main reason as to be rendered having spaced left padding is because in the process of determining y Axis tick value.

Even isn't displayed, the `tick.count` option makes to calculate tick text space as the left screenshot.
I'll be fixing this issue to not count if tick.values option is set.
