### ISSUE TITLE
Legend toggle throws error with x tick rotate and count.

### ISSUE THREAD

**Issue by netil** [naver/billboard.js#1278]
## Description

`Error: <g> attribute transform: Expected number, "translate(NaN,0)".`

## Steps to check or reproduce

```js
bb.generate({
  data: {
    columns: [
      ["data1", 300, 350, 300, 0, 0, 0]
    ]
  },
  axis: {
    x: {
      tick: {
        rotate: 15,
        count: 10
      }
     }
  }
});
```

**Comment by michkami** [comment]
As mentioned in https://github.com/naver/billboard.js/pull/1250#issuecomment-601613365, the bug is not caused by the combination of x tick rotate and x tick count but only by tick count as you can see below: 
![translate_bug](https://user-images.githubusercontent.com/42860868/77151256-d980f500-6a95-11ea-98fc-93e2cff8edde.gif)

**In the following examples I'm using `axis_x_tick_count = 5`.**

The issue are this two lines of code: https://github.com/naver/billboard.js/blob/master/src/axis/AxisRenderer.js#L213-L214
When some data is shown, `tickEnter._groups` will contain some tick nodes so [getTickTransformSetter](https://github.com/naver/billboard.js/blob/master/src/axis/AxisRendererHelper.js#L67) will be called for each tick node.

When all data is hidden, the x axis tick texts are removed from the DOM.
![1](https://user-images.githubusercontent.com/42860868/77159559-df7ed200-6aa5-11ea-9b9e-f5e45403a091.png)
In this case, [getTickTransformSetter](https://github.com/naver/billboard.js/blob/master/src/axis/AxisRendererHelper.js#L67) is called 5 times, because `tickEnter` and `tick` still contain 5 tick nodes. And each time it tries to edit a node that doesn't exist.
In this case the value `d` in `selection.attr("transform", d => fn(Math.ceil(scale(d))))` will be undefined.

If all data is hidden, [ticks](https://github.com/naver/billboard.js/blob/master/src/axis/AxisRenderer.js#L109) contains `undefined` and `Invalid Data` (for timeseries) values (for category and indexed, the array is empty).
Checking if the values in `ticks` are valid and than calling `tickTransform` should eliminate this bug as.
Something like this:
```javascript
const ticksContainsValidValues = ticks.every(value => typeof value === "number" || typeof value === "string" || typeof value === "object");

ticksContainsValidValues && tickTransform(tickEnter, scale0);
ticksContainsValidValues && tickTransform(helperInst.transitionise(tick).style("opacity", "1"), scale1);
```
