### ISSUE TITLE
Labels are removed on unzoom in V2.0.0-next 4

### ISSUE THREAD

**Issue by RonnyWeiss** [naver/billboard.js#1449]
When zoom into chart e.g. by scroll and then call unzoom labels are removed
Could you please fix that.

Chart Json:
[chart.txt](https://github.com/naver/billboard.js/files/4790740/chart.txt)

![2020-06-17_08h36_28](https://user-images.githubusercontent.com/30749177/84863972-32046600-b076-11ea-89fc-2f1ee7ca500c.gif)

And in all Version when zoom the labels are running out of the chart as you can see in gif animation this is in all version is this a bug or a feature? because when legend is right it looks not so nice.

Thank you for fixing so fast the other issues.

Kind regards

Ronny

**Comment by RonnyWeiss** [comment]
I hope I am not annoying with the fact that I am already validating and testing the new V2.0 and reporting every error? :-)

**Comment by netil** [comment]
@RonnyWeiss, your reporting will help to find potential issue during the RC release period.
Plz, don't hesitate posting any issue that comes in mind if you think is not working correctly. :)

Anyway, I'll be try figuring out this, Thanks a lot!

**Comment by netil** [comment]
## The labels are running out

The reason were x Axis tick texts are showing out of the x Axis size is because it should have some space to not cut tick text where is positioned at the end of each corner(left and right).

![image](https://user-images.githubusercontent.com/2178435/85099682-041b4f00-b239-11ea-8a39-d52ccace7e6d.png)

But, from this it will look weird in case you do zoom interaction moving chart back and forth where tick texts are running out the x Axis width size.

I did some updates mitigating giving too much space for each corner, and will work as the below screenshot.

![x-axis-clip-path](https://user-images.githubusercontent.com/2178435/85099716-1d240000-b239-11ea-9180-b985201af2aa.gif)

The label disappearing bug and the mitigation of text running out are updated in `2.0.0-next.5` release.
