### ISSUE TITLE
[critical] Wrong tooltip event coordinate

### ISSUE THREAD

**Issue by netil** [naver/billboard.js#1695]
## Description

Due to the #1642 update, chart tooltip not showing correctly when chart's position changes dynamically.
And also in a cases for rotated axis chart, after doing some page scrolls don't work correctly.

Seems is critical, will be release a patch ASAP.

**Comment by creage** [comment]
@netil we are facing an issue with 2.1.1 - Tooltips are not displayed when we resize `Bar` chart. They are displayed in the area of initial chart size, but when chart is resized - this area remains the same. And moving mouse over the chart **outside** of initial size - does not displays tooltip. 

Can our issue be connected to this one, or do you want me to create new issue on it?

**Comment by netil** [comment]
@creage, can  you provide reproducible code?

**Comment by creage** [comment]
@netil apparently this happens when you set `resize: { auto: false }`. 

We handle chart resizing manually, detecting if there is enough space to render it, and we call `chart.resize(dims)` manually.

If we don't apply `resize: { auto: false }` - everything works fine. But we don't want charts to resize automatically.

**Comment by netil** [comment]
@creage, got it. `resize.auto=false` reproduce the issue.
