### ISSUE TITLE
return values for axis labels

### ISSUE THREAD

**Issue by blazespinnaker** [naver/billboard.js#1865]
```
 Get and set axis labels.
..
labels: function(labels: {x?: string, y?: string, y2?: string}): void {
		const $$ = this.internal;

		if (arguments.length) {
			Object.keys(labels).forEach(axisId => {
				$$.axis.setLabelText(axisId, labels[axisId]);
			});

			$$.axis.updateLabels();
		}
	},
```

should this return a value?  I put 

`return [$$.axis.owner.config.axis_y_label, $$.axis.owner.config.axis_y2_label];`

 in my code, but not sure if that's best so not doing a PR.  Guidance here would be appreciated.
 
 Btw, Is there a list of the TODOs from c3 kept somewhere?  This was one of them. 
 
 Furthermore, would it be possible to give more headline credit to the c3 project on the front page?  
 
 The way c3 is being buried, historically and credit wise, we can't really blame them if they do a reverse fork at this point.  
 
 C3 had some very good ideas that this project has leveraged (docs + examples, fairly simple and accessible API), not to mention all that code (the above is verbatim from c3, minus the TODO comment).  I'd like to use this project but I don't feel that great because of the lack of credit given to c3.  
 
 Plus maybe they will link to billboard if there was more credit given.

**Comment by netil** [comment]
Hi @blazespinnaker, `axis.labels()` not return any value, but as the API description "Get and set axis labels.", returning value will be more reasonable.

> Furthermore, would it be possible to give more headline credit to the c3 project on the front page?

The description of the fork was maintained almost 2yrs, since the start of the project, and I removed(51cdbf48aec8ae898b7150713b0788a702ede4f5) it, because at certain point in terms of the codebase and the functionalities literally I can say C3.js and billboard.js are different libraries now.
(but, anyone can still find the history easily by reading "[Why we decided to start billboard.js?](https://github.com/naver/billboard.js/wiki/Why-we-decided-to-start-billboard.js%3F)")

If you take a look on the examples, docs, and the source code(also the internal architecture), you'll notice the differences done.

> checkout also the [C3 and Billboard](https://github.com/naver/billboard.js/issues/641) issue as the reference.
