### ISSUE TITLE
Why chart broken when unload default datasets?

### ISSUE THREAD

**Issue by h4wldev** [naver/billboard.js#187]
## Description
When i unload **default datasets**(when set generate chart), chart has broken. can tell me what it has problem?

## Steps to check or reproduce
https://codepen.io/anon/pen/aVJzGP

**Comment by netil** [comment]
Check out the note from API doc:
- https://naver.github.io/billboard.js/release/latest/doc/Chart.html#load

> Note: unload should be used if some data needs to be unloaded simultaneously. If you call unload API soon after/before load instead of unload param, chart will not be rendered properly because of cancel of animation.
done will be called after data loaded, but it's not after rendering. It's because rendering will finish after some transition and there is some time lag between loading and rendering

If you need to unload & load data simultaneously, add `unload` key for unload data.
Update your code as below. 

```js
setTimeout(function () {
   /* remove this part 
   chart.unload({
        ids: ['data1', 'data2']
    }) */

	chart.load({
		columns: [
			['data3', 400, 500, 450, 700, 600, 500]
		], unload: ['data1', 'data2']
	});
}, 1000);
```

**Comment by h4wldev** [comment]
I got it. it is my mistake. thx for answer me.
