### ISSUE TITLE
legend.inset.anchor is not working

### ISSUE THREAD

**Issue by OriginJang** [naver/billboard.js#1935]
## Description

- version
  - billboard.js: 2.2.2 and 2.0.3(I tested this two versions)

When I assign `top-right`, `bottom-right` to legend.inset.anchor, the following error occurred.
`TypeError: Cannot read property 'getXAxisTickTextY2Overflow' of undefined`

Here is [chart option](https://codepen.io/KiWonJang/pen/WNGZWON?editors=1111) and you can check for errors in developer tools. Is there an option I need to add to use the anchor option?

<img width="670" alt="스크린샷 2021-02-08 오후 6 27 49" src="https://user-images.githubusercontent.com/30206880/107200679-5b299a80-6a3b-11eb-8139-cdacd6796932.png">

**Comment by michkami** [comment]
It's because of missing `false` in `getCurrentPaddingRight()` in [this line](https://github.com/naver/billboard.js/blob/master/src/ChartInternal/internals/legend.ts#L142)

It can be simply fixed by just adding false, but I would rather refactor  `getCurrentPaddingRight(withoutTickTextOverflow = false)` to `getCurrentPaddingRight(withXAxisTickTextOverflow = false)` in `size.ts` so that [xAxisTickTextOverflow](https://github.com/naver/billboard.js/blob/master/src/ChartInternal/internals/size.ts#L98) will be 0 by default and will be only calculated if needed for autorotating x axis tick texts.

Where do you want to merge it @netil? Master with bb 2.2 or next with d3 v6?

**Comment by netil** [comment]
@michkami, before the `v3` release, every patch updates works need to be done on master.
