### ISSUE TITLE
Cannot use HTML in tooltips

### ISSUE THREAD

**Issue by doug-the-guy** [naver/billboard.js#1948]
## Description
When using custom tooltip formatting with HTML, the literal HTML is displayed.

## Steps to check or reproduce
[jsFiddle](https://jsfiddle.net/8oy79m6x/) w/ billboard 2.2.3 and d3 v4.13

This used to work when I was on c3.js v0.4 because the `sanitise` function (which just escapes < and >) did not exist then. I believe the issue is that the value, say `<em>400</em>` is `sanitised` it produces `&lt;em&gt;400&lt;/em&gt;` which is then mixed in with unescaped html: `<td>&lt;em&gt;400&lt;/em&gt;</td>`.

The way I am using this in my project is overlaying points on a line graph where significant events occur and the tooltip lists them line by line. This is where I would join with a `<br/>`. As a work around, I was able to join by `&#10;` (line feed) and the css:

`
.c3-tooltip {
    white-space: pre-line;
}
`

However this doesn't handle the general case.

I haven't looked too deeply at the code, but perhaps all of the HTML that composes the tooltip should be escaped (`sanitised`) and then use `text()` instead of `html()` (although the former is slower than the latter, but may be moot in this case).

**Comment by netil** [comment]
Sanitizing is needed to prevent from any possible security vulnerability.
The sanitation was applied since C3.js 0.4.11, where billboard.js forked from that version.
- https://github.com/c3js/c3/releases/tag/0.4.11
- https://github.com/c3js/c3/issues/1536

If don't need explicitly add `<em>`, you can make to appear values in italic by doing:

```css
.bb-tooltip .value {
    font-style: italic;
}
```

Or try approaching using [tooltip.contents.template](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.tooltip) option, where you can use HTML freely.
- https://naver.github.io/billboard.js/demo/#Tooltip.TooltipTemplate

**Comment by doug-the-guy** [comment]
Thanks for the suggestion. Is there a way to have tooltips.contents.template apply to the standard hover tooltip?

Here's a [jsFiddle](https://jsfiddle.net/doug_the_guy/sqby93ct/55/) demonstrating the way I'm using HTML i the tooltips for line breaks.

**Comment by netil** [comment]
well, copying the default HTML structure will make to looks same.
`<em>` tag is surrounding value as wanted.

```js
  tooltip: {
	  contents: {
		  template: `<div class='bb-tooltip-container'>
			<table class='bb-tooltip'>
			<tbody>
				<tr><th colspan="2">{=TITLE}</th></tr>
				{{<tr class="{=CLASS_TOOLTIP_NAME}">
					<td class="name"><span style="background-color:{=COLOR}"></span>{=NAME}</td>
					<td class="value"><em>{=VALUE}</em></td>
				</tr>}}
			</tbody></table></div>`
	  }
  }
```
