### ISSUE TITLE
piechart legend/label enhancement

### ISSUE THREAD

**Issue by tjohannto** [naver/billboard.js#1954]
Would it be possible to add these features I added here (pie label background, bounding rect and custom legend using name, ratio and value):

![image](https://user-images.githubusercontent.com/45257386/108487122-2f11e300-729f-11eb-8ca5-c198cfc1c8c5.png)

https://jsfiddle.net/rxj70uka/

to the piecharts manually "onrendered"?

Or is there a smarter and less "costly" or more elegant way to have this features using BB?

p.s. feel free to use anything of this code as you like.

**Comment by michkami** [comment]
Actually, it would be nice to have label backrounds in all chart types.

We are rendering background labels in {{onrendered}} for all types being usable in "Combination Chart" (area, bar, line etc.). The problem is that the background rects have to wait for the text transition to end, so that the texts are moved first and immediately after the transition ends, the background rects are transitioning to the new position.

By implementing the background rects functionality directly into billboard, it would be possible that the texts and the backgrounds would use the same transition.

**Comment by netil** [comment]
@tjohannto @michkami,

using svg [`<filter>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/filter) can make texts to have backgrounds.

<img src=https://user-images.githubusercontent.com/2178435/120753823-b598ba80-c546-11eb-86b4-67500503debc.png width=300>


```js
onafterinit: function() {
	const backgroundColor = "red";
	const defs = this.internal.$el.defs || this.internal.$el.svg
		.insert("defs", ".bb-main");

	defs.append("filter")
		.attr("x", 0)
		.attr("y", 0)
		.attr("width", 1)
		.attr("height", 1)
		.attr("id", "bg")
		.html(`<feFlood flood-color="${backgroundColor}" />
			<feComposite in="SourceGraphic"/>`);

	this.$.text.texts.attr("filter", "url(#bg");
}
```

Adding as new option might facilitate the process.
```js
data: {
    labels: {
        backgroundColor: "red",

        // or specify colors by data series
        backgroundColor: {
                data1: "red",
                data2: "blue"
        }
    }
}
```

**Comment by tjohannto** [comment]
data.labels.backgroundColor and data.labels.format does not seem to apply to pie charts, right?

**Comment by netil** [comment]
@tjohannto, it works for all type of shapes.
> There was a typo from API doc omitting last `s` (it should be "backgourndColors" not "backgroundColor")
<img src=https://user-images.githubusercontent.com/2178435/123890871-f2fc3680-d992-11eb-82b5-e32510f06a6c.png width=300>
