### ISSUE TITLE
Auto-Height like Auto-Width

### ISSUE THREAD

**Issue by adschm** [naver/billboard.js#2086]
When inside any divs without specific size setup, the width of the svg is typically calculated correctly based on the parent container, and the height defaults to 320px. Same happens when I set the parent height with relative values (e.g. "80%"), only using absolute values for the direct parent (500px) loads to a properly sized plot.

I created a "broken" example here (blue background indicates the parent container, where width is inherited but height is not):

https://jsfiddle.net/adschm/vsp1bzun/6/

When looking at the code, it is obvious that width and height have different algorithms:
https://github.com/naver/billboard.js/blob/master/src/ChartInternal/internals/size.ts#L22-L34
https://github.com/naver/billboard.js/blob/master/src/ChartInternal/internals/size.ts#L154-L162

I assume there is a reason for this behavior, but can it be altered to also make the height responsive? Or will I have to work around this by retrieving and setting the height of the parent element via javascript?

**Comment by netil** [comment]
Hi @adschm, well is because when the bound element height isn't specified and following the width's logic, there're possibility to be set bigger than usually expect.

The current logic will check the bound element, if has inline style `height` property with `px` unit value. If has, will take that, or else will be fixed to 350 as height.

To improve this, when user specifies other than `px` unit as your case, make to check bound element's height. (or parent in case of  can't not determine height from the current element)

I'll do the fix, and thanks for the comment.

**Comment by adschm** [comment]
Fix confirmed for explicit height in per cent.

Thanks for taking care!
