### ISSUE TITLE
Multiple consecutive calls to "load" function with "unload = true" param generates a wrongly rendered chart

### ISSUE THREAD

**Issue by miguelCT** [naver/billboard.js#2121]
## Description
Multiple consecutive calls to `load` function with `unload = true` param generates a wrongly rendered chart.

## Steps to check or reproduce
https://codesandbox.io/s/billboardjs-render-problems-exd4k?file=/src/index.ts:584-755

In the provided example, the function `load` is called 2 times after the first render. As you can see, there's only a difference of 100ms between both calls. The expected result of this calls should generate a chart where only the last dataset is rendered, but the actual result is a wrong mix of both datasets.

If you force the render of the last dataset after more than 100ms, the chart renders correctly.

### Expected result

![image](https://user-images.githubusercontent.com/7680090/120617079-b3086900-c451-11eb-8f00-4191189d007a.png)

### Actual result

![image](https://user-images.githubusercontent.com/7680090/120617170-c6b3cf80-c451-11eb-9397-10fa2c362336.png)

> You can even see that the tooltip does not even match the current rendered chart

#### Additionally
I've tried to set `transition.duration = 0` to discard animation cancel problems, but it does not apply when you `unload` data, only in `load`. Is that correct?

**Comment by netil** [comment]
Hi @miguelCT, thanks for the report. I'll check the issue.

**Comment by netil** [comment]
If you want load right after, consider using `done` callback option as below. This will guarantee correct rendering

<img src=https://user-images.githubusercontent.com/2178435/120737676-790a9600-c529-11eb-89e4-47d98972c1a3.gif width=300>

```js
var chart = bb.generate({
  data: {
    columns: [
      ["data1", 30, 200, 100, 400, 150, 250],
      ["data2", 50, 20, 10, 40, 15, 25]
    ],
    type: line()
  },
});

setTimeout(function () {
  chart.load({
    columns: [["data1", 230, 190, 300, 500, 300, 400]],
    unload: true,
	done: function() {
		this.load({
			columns: [["data3", 130, 150, 200, 300, 200, 100]],
			unload: true
		});
	}
  });
}, 1000);
```

**Comment by miguelCT** [comment]
First of all, thanks for the response!

I have a couple of concerns:
1. I would say that the `done` function fits when you know how many `loads` in the chart you will have. But what if the `load` depends on a user input, where you don't have any control on how many re-loads you will have to do? I would say that in this case the `done` function does not quite fit. Or maybe I couldn't wrap my head around it properly... 

2. Calling `load` inside the `done` function does the trick, but somehow I was expecting that the own `load` function + `unload: true` would do exactly what I want to achieve: _"unload the data from before, no matter how many times or how fast the load function was called"_. The `done` callback is useful when you want to know when the load has finished, but it seems a bit off having to call the `load` function inside of the own `load` function.

**Comment by FjVillar** [comment]
Hi there, 

I think I`m in the same problem here. I have seen this happening more frequently using Billboard.js with React. After seeing this issue and investigating it a bit, I would say that this could be a problem with the use of `d3-transition` package of Billboard.js. 

What I think it's happening is that when the second load it's triggered there is a transition going on and Billboard it's trying to start a new transition while the other hasn't ended yet. Here there are some [related issues](https://stackoverflow.com/questions/26903355/how-to-cancel-scheduled-transition-in-d3/26904293#26904293) of people trying to solve similar problems like this one but with `d3` itself.

We are suffering from this problem in a real-case scenario. We are requesting an API for data that it's loading very fast. And we have been forced to change our code in order to avoid fast renders while loading data to our charts. This solution we have made feels like a workaround more than a solution for us. 

I hope @miguelCT and @netil find this comment useful, also I wanted to thank you for this amazing library :D

**Comment by netil** [comment]
as @FjVillar mentioned, this is how cumbersome solve when some task is triggered during the transition.
One of the way to guarantee is by approaching with `done` callback. 
I'll be improve this to  mitigate this when `transition.duration=0` option is set.

> also I wanted to thank you for this amazing library :D

BTW, @FjVillar thanks for the comment!
