### ISSUE TITLE
Gauge: title not updated

### ISSUE THREAD

**Issue by adschm** [naver/billboard.js#2124]
Due to the bug in #2123 I'm using the multi-type gauge for displaying a single arc. With this, I can fake a pseudo-single-type gauge by using title for displaying the current value and setting label to "":

https://jsfiddle.net/adschm/sqkuoat9/6/

Unfortunately, this only works for a non-dynamic case, since I was not able to update the value with:
* chart.config("gauge.title",something) + chart.load(...) afterwards
* chart.config("gauge.title",something,true)
* chart.config("gauge.title",something) + chart.flush() afterwards

Am I doing something wrong or is this a bug (or simply not intended to have an adjustable title...?).

The optimal case for this scenario would obviously be to have the option of setting title to a function(id), so one could just select the data from a specific row dynamically and not have update at all (roughly similar to gauge.label.format).

**Comment by netil** [comment]
First of all, fixed the issue #2123. So, by calling `.load()` will make to update title area.

Coming back to the issue where `.config()` not updating `gauge.title`, is because `.config()` call not always can update in all circumstances(this was added as "NOTE" in API doc). To make this happen for all config values, it needs to re-initialize from the start of the generation(like re-generating nodes already generated, etc.) of chart, which isn't necessary(or inefficient).

For this specific case, manipulating title node directly, will work as your needs.

![Kapture 2021-06-10 at 10 44 36](https://user-images.githubusercontent.com/2178435/121451620-e3638080-c9d8-11eb-9f0f-75039a90e9f0.gif)


```js
  onrendered: function() {
        // will render a random number on every rendering
	this.$.arc.select(".bb-chart-arcs-gauge-title")
		.text(
			Math.random().toFixed(2)
		);
  }
```

**Comment by adschm** [comment]
Okay, I understand the reasoning. I assume setting gauge.title to a function would not make sense under these circumstances as the function would not be reevaluated during data refresh for the same reasons (or, it would not be reasonable to implement such an evaluation due to the reasons given)?

My actual hack for the moment was setting the title via jQuery after chart.load():

```
$("#mychartid text.bb-chart-arcs-gauge-title").text(
      Math.random().toFixed(2)
);
```

Are there any benefits of using the onrendered approach or would the choice be arbitrary?

**Comment by netil** [comment]
`onrendered` is called whenever the "redraw" happens(like new data loads, resize, etc) and also can select current chart context elements directly without any other helpers.
If needs to update title text just once, [`onafterinit`](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.onafterinit) would be more adequate option.

**Comment by adschm** [comment]
Thanks for the pointers. Since this is marked "won't fix", we might as well close it.
