### ISSUE TITLE
Setting x.axis.tick.fit to false displays wrong time when localtime is false

### ISSUE THREAD

**Issue by arajcok** [naver/billboard.js#2186]
## Description
When setting `axis.x.localtime` to `false`, the axis tick displays the correct time. However, if in addition to that you set `axis.x.tick.fit` to `false` (to use d3's tick scale behavior), the axis tick displays the wrong time. Specifically, whenever there is a new day, month, year, etc., it displays the date based on localtime. 

On a related note, it also seems to decide the placement of the tick marks based on localtime, rather than UTC.

## Steps to check or reproduce
```javascript
bb.generate({
  data: {
    x: 'x',
    columns: [
      ['x', 1356998400000, 1357084800000, 1357171200000, 1357257600000, 1357344000000, 1357430400000],
      ['data1', 30, 200, 100, 400, 150],
      ['data2', 130, 340, 200, 500, 250, 350]
    ],
    type: "line"
  },
  axis: {
    x: {
      localtime: false,
      type: "timeseries",
      tick: {
        fit: false
      }
    }
  },
  subchart: {
    show: true,
  },
  bindto: "#chart"
});
```
![image](https://user-images.githubusercontent.com/36488253/125699280-770fec18-e152-4172-83e5-1cc6797bcbe7.png)

**Comment by netil** [comment]
Hi @arajcok, thanks for the report.

When `axis.x.localtime` option is true, will scale based on the [d3.scaleTime](https://github.com/d3/d3-scale#scaleTime) and when is false, is should be treat x Axis scale based on [d3.scaleUtc](https://github.com/d3/d3-scale#scaleUtc). 

But even set `axis.x.localtime=false`, it was scaling based on the `d3.scalTime` rather than `d3.scalUtc`.
I'll fix that issue, but if you set `tick.fit=false` the x Axis tick will be generated using d3's [.ticks()](https://github.com/d3/d3-scale#time_ticks).

Based on the data example you provided, will generate ticks as follows.
- https://github.com/naver/billboard.js/blob/master/src/ChartInternal/Axis/AxisRendererHelper.ts#L122-L123

```js
 x: {
      localtime: false,
      type: "timeseries",
      tick: {
        fit: false
      }
    }

==> [
    Tue Jan 01 2013 09:00:00 GMT+0900,
    Tue Jan 01 2013 21:00:00 GMT+0900,
    Wed Jan 02 2013 09:00:00 GMT+0900,
    Wed Jan 02 2013 21:00:00 GMT+0900,
    Thu Jan 03 2013 09:00:00 GMT+0900,
    Thu Jan 03 2013 21:00:00 GMT+0900,
    Fri Jan 04 2013 09:00:00 GMT+0900,
    Fri Jan 04 2013 21:00:00 GMT+0900,
    Sat Jan 05 2013 09:00:00 GMT+0900,
    Sat Jan 05 2013 21:00:00 GMT+0900,
    Sun Jan 06 2013 09:00:00 GMT+0900
]
```

```js
    x: {
      localtime: true,
      type: "timeseries",
      tick: {
        fit: false
      }
    }

==> [
    Tue Jan 01 2013 12:00:00 GMT+0900,
    Wed Jan 02 2013 00:00:00 GMT+0900,
    Wed Jan 02 2013 12:00:00 GMT+0900,
    Thu Jan 03 2013 00:00:00 GMT+0900,
    Thu Jan 03 2013 12:00:00 GMT+0900,
    Fri Jan 04 2013 00:00:00 GMT+0900,
    Fri Jan 04 2013 12:00:00 GMT+0900,
    Sat Jan 05 2013 00:00:00 GMT+0900,
    Sat Jan 05 2013 12:00:00 GMT+0900,
    Sun Jan 06 2013 00:00:00 GMT+0900
]
```
