### ISSUE TITLE
Line chart Y axis step is broken

### ISSUE THREAD

**Issue by cosmo0** [naver/billboard.js#2294]
## Description
When setting Y axis step to `1` in a line chart, it displays steps as 0.1 increments

## Steps to check or reproduce

https://jsfiddle.net/cosmo0/xkwav32z/14/

![image](https://user-images.githubusercontent.com/3973850/131475755-c05cfe02-bc22-4289-8413-721fc4690e28.png)

**Comment by adschm** [comment]
Hmm, the _increment_ is actually correct. E.g. 4.1 -> 5.1 has an increment of 1.

Your problem is not the increment, but the offset.

I could fix the behavior by using `result.axis.y = { tick: { stepSize: 1 }, padding:0 };` in your fiddle.

This can be combined with specific values for min/max.

However, I do agree that something is wrong here, but this is probably an effect of the implementation of "padding".

**Comment by netil** [comment]
@cosmo0 thanks for the report and thanks @adschm for the workarond.
I'll be checking the issue.

**Comment by cosmo0** [comment]
I can confirm it now works with 3.2.0-next.6.

Thanks!
