### ISSUE TITLE
Data labels are shown when data.labels.show is set with false explicitly

### ISSUE THREAD

**Issue by 5r1m** [naver/billboard.js#2296]
## Description
Data labels are shown even when data.labels.show is set with false. By default, this would be false, but still it is expected to work as expected when set with false explicitly.

## Steps to check or reproduce
https://codepen.io/5r1m/pen/bGRevKY

**Comment by 5r1m** [comment]
Looking at hasDataLabel (https://github.com/naver/billboard.js/blob/master/src/ChartInternal/data/data.ts#L651), it looks like it checks for boolean and true or just a non empty object. Re-looking at the documentation has confirmed and probably got confused me on first read. It would have been good if we can even use show property even with object, but I would not insist as this is trivial and may be your time can go in to something more important.

If this is how its designed, then would close this.

**Comment by netil** [comment]
Hi @5r1m, there's no `data.labels.show` option.
To disable data label text, you need set `data: { labels:false }`, otherwise setting data labels' option will enable the display of labels.

Checkout the API doc:
- https://naver.github.io/billboard.js/release/latest/doc/Options.html#.data%25E2%2580%25A4labels

**Comment by 5r1m** [comment]
Thanks @netil. Closing this issue as it is working as documented.
