### ISSUE TITLE
Tooltip is not shown when point and grouped are set as false

### ISSUE THREAD

**Issue by 5r1m** [naver/billboard.js#2388]
## Description
Tooltip is not shown when point and grouped are set to false. This can be reproduce by adding the required config in:
https://naver.github.io/billboard.js/demo/#Chart.TimeseriesChart

Config:
line : { point : false },
tooltip:{ grouped: false}

I am trying to show a custom tooltip with this configuration when clicked on anywhere on the line and not just at point

Strangely tooltip is not shown in codepen even with out any modifications from the example. Is this expected?
## Steps to check or reproduce
https://codepen.io/5r1m/pen/JjyWzKe

**Comment by netil** [comment]
> clicking anywhere on line.

basically, tooltip need to be correlated with the correct data point position. Because tooltip is for displaying data values from the visualized shape. Not knowing what data need to display is an ambiguous approach.

I'm not sure what do you want to achieve, if just want display tooltip content without showing correlated data values, you can bind some custom event for line element directly.

**Comment by 5r1m** [comment]
Thanks @netil. That was my fallback approach but I guess will have to take that path.
