### ISSUE TITLE
Types are not updates to reflect plugin

### ISSUE THREAD

**Issue by ccollie** [naver/billboard.js#2464]
## Description
the type file `bb.d.ts` is not updated to reflect the `plugin` map

## Steps to check or reproduce
see https://github.com/naver/billboard.js/blob/2052a19af7fae25688a182e1d5244e523ed1f3cc/types/bb.d.ts#L8

**Comment by netil** [comment]
Hi @ccollie, will not expose [`bb.plugin`](https://naver.github.io/billboard.js/release/latest/doc/bb.html#.plugin) from the definition, because it is the namespace reserved for `<script>` loading environment.

In case of TS environment, the plugin will be consumed as ESM which isn't necessary approach via `bb.plugin.plugin-name`.
