### ISSUE TITLE
Updating color pattern in config post render is not working

### ISSUE THREAD

**Issue by 5r1m** [naver/billboard.js#2492]
## Description
Updating the color patterns using config update is not working if updated after the first render.

## Steps to check or reproduce
https://codepen.io/5r1m/pen/eYGKQwm

**Comment by netil** [comment]
`.config()` get and sets config object values and redraws, if the last param is true.
But, it has limitation where can't not reflect all the config values, because option values are treated across the entire process. If some config values are used only at the initialization, is obvious that can't be applied even config object value updated after.

So, from that reason API doc states as:
> NOTE: Doesn't guarantee work in all circumstances. It can be applied for limited options only.

If you want change colors of data, try using `.data.colors()` API.
```js
chart.data.colors({
   data1: "red",
   data2: "red",
   data3: "red
});
```

**Comment by 5r1m** [comment]
Thanks @netil  for the explanation and will close this as this is unsupported and have multiple alternatives.
