### ISSUE TITLE
Tooltip in browser does not work anymore?

### ISSUE THREAD

**Issue by mxxrten** [naver/billboard.js#2550]
## Description
The tooltip when hovering in the chart does not show anymore in the examples page. It was working last friday. Maybe because of the new 3.3.2 release 9 hours ago?

## Steps to check or reproduce
Hovering mouse in chart does not show tooltip. For example on this page:
https://naver.github.io/billboard.js/demo/#Chart.LineChart

When in Chrome pressing F12 and enable mobile preview then it does work again:
![image](https://user-images.githubusercontent.com/3768742/153884925-f8850388-aaee-42c2-bf55-8423b01ae363.png)

Tested with up to date Chrome, Edge and Firefox.

**Comment by netil** [comment]
Hi @mxxrten, tested on chrome(mac & windows), edge, safari and couldn't reproduce the issue.
Try with cleaning up local caches and if not working, provide exact environment info you're using.

![Kapture 2022-02-15 at 10 28 33](https://user-images.githubusercontent.com/2178435/153975345-2caaca51-6204-44dc-b3c4-02f6ef34c012.gif)

**Comment by mxxrten** [comment]
Thank you for the reply. I tried incognito in Chrome on Windows and clear the cache. 
bb.version is 3.3.2.
I see that billboard.js and billboard.css get a 404
![image](https://user-images.githubusercontent.com/3768742/154014524-3519bb3d-59b4-4558-b5b0-39e1afc5943b.png)

![billboard js broken2](https://user-images.githubusercontent.com/3768742/154015626-5b63acfc-7327-4a88-81bf-4229955cf9bf.gif)

**Comment by netil** [comment]
> I see that billboard.js and billboard.css get a 404

Fallbacks are applied on loading assets. Is because the path on dev local environment and the production is different and is nothing about affecting tooltip interaction at all.

I tested on 2 macs(iMac and Macbook pro) and one windows laptop, none of them were reproducible the issue.
If someone else experiencing same issue, please share it by the comments.

**Comment by hjalmers** [comment]
@netil I can reproduce the issue and it seems to occur on laptops with touch screens so I assume they're treated as mobile devices. I think the issue was introduced with this commit 👉  https://github.com/naver/billboard.js/commit/0ae640a53edc045018df341a93e4fe91366268f8. I could have a go at it and make a pull request if you want @netil?

**Comment by mxxrten** [comment]
To confirm, I have indeed a Dell laptop with touchscreen.

**Comment by netil** [comment]
> it seems to occur on laptops with touch screens

Seems occurring in that case.  I don't possess any touch screen laptop for the real test, but according to the PR sent by @hjalmers can handle this properly.

@mxxrten, checkout the `nightly` build later if the issue has been fixed.
- https://github.com/naver/billboard.js#nightly-version
