### ISSUE TITLE
Question: Show value and percentage on Donut chart

### ISSUE THREAD

**Issue by de-don** [naver/billboard.js#2624]
## Description
Is it possible to show NAME, VALUE and PERCENTAGE in tooltip on Donut Chart?

With `fomat` option, I can show one of values: VALUE or PERCENTAGE.

I need something like this:
![image](https://user-images.githubusercontent.com/14067329/161752908-a6f7c4b6-65ae-425c-b1d4-8d90ae3b7cb7.png)

In `contents.template` I have only NAME & VALUE (no TITLE) :(

**Comment by netil** [comment]
Hi @de-don, `{=TITLE}` isn't provided for arc(pie, donut, gauge) types, because title value is to show corresponding x axis value,  which arc types don't have axis.

If you need to fully customize tooltip contents, approach by [`tooltip.contents`](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.tooltip) option. `tooltip.format` options are to just format values, not for customize the content.

checkout the example I made as a reference.
- https://jsfiddle.net/netil/nbsyexap/

**Comment by de-don** [comment]
@netil Thanks, I have already solved the problem using the `contents` method.
This is really a more flexible and readable solution than using a template :D

I got something like this
```js
function getContents(data) {
  const item = _.head(data);
  if (!item) {
    return '';
  }
  // ... come calculations

  return (
    '<div class="bb-tooltip">' +
    `  <div class="name">${name}</div>` +
    '  <div class="values">' +
    `    <div class="value">${value}</div>` +
    `    <div class="percent">${percent}</div>` +
    '  </div>' +
    '</div>'
  );
}
```
