### ISSUE TITLE
Rendering issue in bar chart when using bar -> radius -> ratio

### ISSUE THREAD

**Issue by Nicolas469** [naver/billboard.js#2642]
## Description
Rendering issue in bar chart when using bar -> radius -> ratio.
This arises only when we update a value to "0".

## Steps to check or reproduce
Just check this example: https://stackblitz.com/edit/21bdn7?file=index.ts then uncomment line 23 to see the bug.

**Comment by netil** [comment]
Hi @Nicolas469, the example you share, I see the `data.labels.centered` option is set. 
When this option is set, it means data label texts appearing on each bars, positioned at the vertically centered.

If you want hide the text, just set `data.labels=false` or set formatter function as below.

```js
data: {
    labels: {
      format: v => v > 0 ? v : ""
   }
}
```

**Comment by Nicolas469** [comment]
Hi,

I've tried `data.labels=false` and `format: v => v > 0 ? v : ""` but I've got the same bug.
It's only when I comment the `"ratio": 0` that the problem disapear.

**Comment by netil** [comment]
@Nicolas469, there was misunderstanding on this. 
I think you pointed the issue when the data dynamically updates from some positive value to zero, during the transition appears some broken shape during the changes.

It happens, because the rounded shape contains arc path data, but when going to data zero it removes arc path data. Where the issue comes from.

I'll be trying fix(or mitigate) the broken shape's transition.

**Comment by Nicolas469** [comment]
Any news for this bug ?

**Comment by netil** [comment]
@Nicolas469 fixed the issue.

**Comment by Nicolas469** [comment]
Nice, thank you !
