### ISSUE TITLE
Add shapes to legend

### ISSUE THREAD

**Issue by ghost** [naver/billboard.js#269]
Is it possible to make the markers the same for both the points and the label representing the points?

from the playground:
```js
{
    "data": {
        "columns": [
            ["data1", 30, 200, 100, 400, 150],
            ["data2", 50, 20, 10, 40, 15],
            ["data3", 50, 20, 10, 40, 15],
            ["data4", 30, 200, 130, 400, 30],
            ["data5", 50, 20, 10, 40, 415]
        ],
        "type": "scatter"
    },
    "point": {
         pattern: [
          "rectangle",
          "circle",
          "<polygon points='2.5 0 0 2.5 2.5 5 5 2.5 2.5 0'></polygon>",
          "<polygon points='2.5 0 0 5 5 5'></polygon>"
        ]
    }
}
```
However this does not change the labels to match the values shape.
If this is already a feature, the documentation is unclear atm.

Found:
[https://github.com/naver/billboard.js/issues/209](https://github.com/naver/billboard.js/issues/209)

But this does not include a scatterplot.

Lovely continuation from c3js!
Cheers

**Comment by netil** [comment]
The point.pattern was introduced since last release and the legend doesn't reflect the shape of the point.
However, you can construct customized legend to be aligned as the data points.

![image](https://user-images.githubusercontent.com/2178435/35718950-3259c560-082a-11e8-99fe-de1597d45469.png)

It's not really clear solution. Just take this for consideration.
- https://jsbin.com/morosaq/2/edit?html,js,output

**Comment by BrattPurrie** [comment]
Thanks for example.
Greatly appreciated!

- Maybe not a bad feature to expand on this topic?

**Comment by julien** [comment]
Hey @netil, 
What would you think of having this built-in. I don't think it would be too much of a problem and I'd be glad to finish the work ;)

**Comment by netil** [comment]
Sure @julien :)
