### ISSUE TITLE
Comma in generated markup for custom tooltip

### ISSUE THREAD

**Issue by rtmalone** [naver/billboard.js#275]
## Description
I'm tying to style a custom tooltip with the following:
```js
  tooltip: {
    grouped: true,
    contents: function (data, title, value, color) {
      console.log('contents', data)

      return `<div class='custom-tooltip'>
        <h3 class='heading'>${title(data[0].x)}</h3>
        <div class='custom-tooltip-data'>
          ${data.map((d, i) => {
            return `<div><span style='background: ${color(d.id)};'></span>${d.value} ${d.id}</div>`
          })} 
        </div>       
      <div>`
    }
  }
```
Unfortunately, a comma is inserted after every `div` created by the map.

## Steps to check or reproduce
This pen displays the issue:

https://codepen.io/rtmalone/pen/JpXMad

**Comment by netil** [comment]
@rtmalone, well is because you are converting Array to string directly.

Array.map will return a new Array and if this is concatenated with the string will insert a comma in each item. Is like doing as `[1,2,3].toString()` and this will return `1,2,3`.
```js
${data.map((d, i) => {
	return `<div><span style='background: ${color(d.id)};'></span>${d.value} ${d.id}</div>`
})} 
```

So, put the `join("")` to prevent unexpected comma insertion.
```js
${data.map(d => `<div><span style='background: ${color(d.id)};'></span>${d.value} ${d.id}</div>`).join("")}
```

**Comment by rtmalone** [comment]
Ah, that's right. Thank you!
