### ISSUE TITLE
Some top grid lines are missing when min value of y axis is set

### ISSUE THREAD

**Issue by piotrp** [naver/billboard.js#2809]
## Description
Using `axis․y․min` may result in missing grid lines:
![obraz](https://user-images.githubusercontent.com/1409807/182442241-97678fd7-eaf2-4f31-80c8-586162ca0b8a.png)

I would expect each tick on y axis to have its own line, but depending source values some lines may be missing.

## Steps to check or reproduce
JSFiddle: https://jsfiddle.net/vc0hux95/

```js
bb.generate({
  data: {
    columns: [
	    ["data1", 130, 340, 200, 500, 250, 350]
    ],
    type: "line"
  },
  axis: {
    y: {
      min: 0
    }
  },
  grid: {
    y: {
      show: true
    }
  },
  bindto: "#lineChart"
});
```

**Comment by netil** [comment]
This could be a side effect from the changes of #2715. 
I'll look into. @piotrp thanks for the report.

**Comment by netil** [comment]
@piotrp 
After digging, found that the issue happens because of `grid.y.ticks` option default value.
The option has `10` as default value, which limiting display 10 grid lines.

For workaround, give some value greater than the y axis tick count as `grid.y.ticks=20`.

Defaulting to grid ticks count to 10, seems counter intuitive.
Because, when `grid.y.show=true` is set, user will expect to be shown full grid lines. 

Removing default value looks more reasonable in this case.
