### ISSUE TITLE
legend template arguments

### ISSUE THREAD

**Issue by julien** [naver/billboard.js#302]
## Description

When using  the `template.contents.legend` option, two values (`title` and `color`) are received, which limits what one can "render" in the legend.

I'd like to render a pie chart, showing the pie's values in the legend, and to acheive this, I'm using this code. 

```javascript
const chart = bb.generate({
  data: {
    columns: [
      ['data1',  200],
      ['data2',  4000],
      ['data3',  600],
    ],
    type: 'pie'
  },
  legend: {
    contents: {
      bindto: '#legend',
      template(title, color) {
        const data = this.api.data(title)[0].values.map(v => `${v.value} %`).join(' ');
        return `<div><span style="background:${color}">${title}</span>
           <span>${data}</span></div>`;
      }
    }
  },
  bindto: '#chart'
});
```

This renders something like the image bellow

<img width="390" alt="pie_legend_values" src="https://user-images.githubusercontent.com/5572/36474428-c00e3126-16f7-11e8-88c2-93fe99f78fcc.png">

So, I was wondering if it wouldn't be possible to receive more arguments in the `legend.contents.template` function, like the *percentage value* so that one could use something like this

```javascript
const chart = bb.generate({
  // ...
  legend: {
    contents: {
      bindto: '#legend',
      template: function(title, color, percentageValue) {
        return `<div>${title} accounts for ${percentageValue} of the total exports</div>`;
      }
    }
  },
// ...
});
```

What do you think?
Thanks.

**Comment by netil** [comment]
Well, giving additional parameters aren't bad, but thinking what parameters to provide is another issue.

For legend, in general way is used to display to match the colored chart area with the data name.
I think this is the basic usage of legend. Is quite obvious, having a lot of different needs depend the use cases, but what to provide or not?

Instead of providing a specific param data, providing a general data(like `datum`) can be useful in terms of letting users manipulate them maybe.

What is your thought?

**Comment by julien** [comment]
@netil, yes that seems like a good solution.

Thanks!
