### ISSUE TITLE
Data (and hover legend) not Visible at first

### ISSUE THREAD

**Issue by radiantone** [naver/billboard.js#307]
## Description
I load data into my 2 axis bar chart, but initially it does not appear. When I click an axis in the legend, then the other axis will appear yet the hover legend tooltip no longer appears. Turning the axis on/off in the legend produces some weird output as the data seems to be moving around.

## Steps to check or reproduce
Bottom chart in this fiddle.
https://jsfiddle.net/7ray9day/20/

**Comment by netil** [comment]
Is because, there's a wrong format x data bound.
You pointed to format x as :
```js
xFormat: '%Y-%m-%dT%H:%M:%S.%LZ',
```
Datetime data should be something like `2018-02-22T12:32:52.206Z`, but there's a `2018-02-22T12:30:46Z` which is causing error at the initialization.

![image](https://user-images.githubusercontent.com/2178435/36655135-35de5498-1b04-11e8-8398-0f1ac2d5dbf3.png)

Correct your data to match with the `xFormat` specifier as `2018-02-22T12:30:46.0Z` and will work.
