### ISSUE TITLE
Vulnerability on Billboard 1.x

### ISSUE THREAD

**Issue by nirmal93guna** [naver/billboard.js#3073]
## Description
We are still using Billboard 1.95 with some custom components in our application. Due to this reason we were not able to upgrade to Billboard 2.x or 3.x.
We recently found out that Billboard 1.95 uses d3-color@1.4.1 which has a security vulnerability. Can we expect a patch on Billboard 1.x for this issue?

**Comment by netil** [comment]
Hi @nirmal93guna, [`d3-color` vulnerability issue](https://security.snyk.io/package/npm/d3-color/1.4.1) existed from `d3-color@1.x` and it was fixed from `3.1.0`.
And the problem is, it can't upgrade only d3-color packages from the dependency, without upgrading other d3 packages to `v3`.

IMO, the realistic way to provide a patch, is removing d3-color usage from the 1.x codebase.
And if that is possible, will be released as `1.12.12`.

**Comment by netil** [comment]
@nirmal93guna, released patch as `v1.12.12`.
```sh
$ npm i billboard.js@1.12.12
```

The patch release removed `d3-color` package from the dependency.

**Comment by nirmal93guna** [comment]
@netil Thank you so much for the patch. We will test this version in our product.

**Comment by vivekKodira** [comment]
An update. Unfortunately, d3-color@1.4.1 is still an indirect dependency. We will explore other alternatives:

packages.json:
```
{
  "name": "dummy_project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "billboard.js": "^1.12.12"
  }
}
```
npm ls d3-color
```
└─┬ billboard.js@1.12.12
  ├─┬ d3-interpolate@1.4.0
  │ └── d3-color@1.4.1
  └─┬ d3-transition@1.3.2
    └── d3-color@1.4.1 deduped
```

**Comment by netil** [comment]
@vivekKodira, the best way is using latest version of billboard.js.

IMO, the reason of using older version of billboard.js, is because the users for some reason can't upgrade d3.js version.  
It can't be fixed billboard.js `1.x` to use d3-color@3.1.0, because the work for that eventually will make whole codebase to upgrade all the d3's packages and those works are done on latest version of billboard.js.

So, the way to get rid any possible vulnerability is to upgrading to latest version.
