### ISSUE TITLE
[1.3.0+] window becomes undefined after importing Billboard.js

### ISSUE THREAD

**Issue by boris-petrov** [naver/billboard.js#334]
This may be connected with https://github.com/naver/billboard.js/issues/305.

I have no idea what's going on but updating to `1.3.0` made all our FE tests fail with `QUnit is undefined`. Obviously QUnit is not registered correctly. While debugging, I see for some reason `window` is undefined when `QUnit` is setup which I don't even understand how is possible... not sure how to help more. As in the other issue - we're using Ember CLI and just importing Billboard.js.

[Here](https://github.com/boris-petrov/billboard.js-bug) is a reproduction. I've just done an `ember new some-name`, I changed the test launcher to be `chromium` instead of `Chrome` (as I'm on Linux) and I installed/imported Billboard. Running `ember test` in this project doesn't work now.

**Comment by netil** [comment]
Hmm... weird. Basically, there's no difference on module definition between 12.0 and 1.3.0.

- https://github.com/naver/billboard.js/blob/1.2.0/dist/billboard.js#L10-L18
- https://github.com/naver/billboard.js/blob/1.3.0/dist/billboard.js#L10-L18

Probably it's because of dev-env settings, but before to dig I can't tell what are the cause of the issue.

**Comment by boris-petrov** [comment]
@netil - thanks for the response! You saw the reproduction project, right? Please tell me if you need more information as to how to do that exactly. And also keep in mind that #305 could be coming from the same issue.

**Comment by boris-petrov** [comment]
Just a note - the same issue happens with `1.4.0`. Didn't happen in `1.2.0`.

**Comment by boris-petrov** [comment]
This has been fixed since.
