### ISSUE TITLE
subchart.init.range[0] does not match with the finally set range on timeseries

### ISSUE THREAD

**Issue by Meffesino** [naver/billboard.js#3347]
## Description
When I generate a chart with:

```
  subchart: {
    show: "subchart", 
    showHandle: false,
    init: {
      range: [
        new Date("2018-06-27T00:00:00.000Z").getTime(),
        new Date("2018-06-29T00:00:00.000Z").getTime()
      ]
    },
    onbrush: (brush) => {
     console.log(brush)
    }
  }
```

The onbrush events outputs the wrong min value. It is always off by a few minutes / hours. While max value fits perfectly.

## Steps to check or reproduce
[code pen example](https://codepen.io/Meffesino/pen/YzdKvmY)

The console shows in my case: `"Brush min dimension: 1530057790850 should be 1530057600000 ==> Mismatch: 190850"`

**Comment by netil** [comment]
@Meffesino,

Zoom and subchart precisions aren't returning exact value, due to the limitations of floating point precision.
The scale value will returns approximately values.
- Ref.
  - https://github.com/d3/d3-scale/issues/161#issuecomment-459420221
  - https://github.com/d3/d3-scale#continuous_invert

I'll be adding some adjustment when range domains are given(by API call, or specifying range as `subchart.init.range`), without any zoom changes to return given values.
