### ISSUE TITLE
Decimal values tick labels should have an option to keep number of decimals for all ticks (keep right-padding 0)

### ISSUE THREAD

**Issue by heppa** [naver/billboard.js#3455]
## Description
When there are decimals on axis tick labels, it should be somehow possible to ask for right-padding 0, as it's sometimes difficult to read the axis:
![image](https://github.com/naver/billboard.js/assets/7996084/109799ab-e24b-478b-95b9-0b8e03967f6f)

when we have 2.5, we should also display 3.0, when there is 2.34, it should also be 4.50 and so on and so forth.

## Steps to check or reproduce
Have axis tick values with decimals (either automatically generated or explicitly like in the JSFiddle below):
https://jsfiddle.net/heppa/weh8o9pk/2/ 

This is a simplified example, which would be easy to solve, but it's especially about the automatically generated ticks.

Of course I know, that I can set a format for the tick labels, but it's not possible to format each tick by knowing the maximum number of decimals displayed for example. When I set a fixed number of decimals of 2 decimals for example and the automatically generated ticks are with 3 decimals, I get two ticks with the same label.

Many thanks for looking into this. If you need more information, please get back to me.

**Comment by netil** [comment]
Hi @heppa, thanks for the suggestion.
I tried testing if suggested feature is useful, but concluded that isn't good in all circumstances.

For those ticks having few float decimals, probably will make more readable. But to be implemented, it needs consider in all circumstances, which having different decimals.

I tried in a case, having more than 10 decimals and it will looks like more confusing to read integer numbers, because of zero number added to it.

Below screenshot is the example where having max of 16 decimals and applied 16 zeros to integer numbers. Zero as a character occupy max width dimension among number characters and makes a "peak" compared other decimal ticks.

<img width="305" alt="image" src="https://github.com/naver/billboard.js/assets/2178435/7c29dd5a-88b9-4d7e-8b85-e8230b7732ae">

Probably providing as an option which user can decide to apply or not, but I can't find any good usability of it.

**Comment by heppa** [comment]
Hi @netil,

thanks for analyzing this issue... I understand your point. While it might make sense for 2 or 3 decimals and it would probably seem to be a block there, it might not work depending on the decimals chosen.

Many thanks for this awesome library! ;)

Take care.
