### ISSUE TITLE
3.10 regression: the legend at the bottom overlaps the diagram if padding-bottom is set

### ISSUE THREAD

**Issue by dscheg** [naver/billboard.js#3493]
## Description
Seems that in 3.10.x the height of the chart is calculated without taking into account the legend at the bottom (if padding bottom set for the chart), so legend overlaps the content

## Steps to check or reproduce
```js
var chart = bb.generate({
  padding: {top: 20, bottom: 1}, // <-- (!)
  data: {
    columns: [
	["data1", 300, 350, 300, 0, 0, 0],
	["data2", 130, 100, 140, 200, 150, 50]
    ],
    types: {
      data1: "area",
      data2: "area-spline",
    }
  },
  bindto: "#areaChart"
});
```
![image](https://github.com/naver/billboard.js/assets/1962268/1b7e222b-7e4d-441b-8c00-ba7c05597625)

**Comment by netil** [comment]
Hi @dscheg, applying of `padding` options has been re-organized.

Please read [Understanding padding](https://github.com/naver/billboard.js/wiki/Understanding-padding#specifying-padding-values) documentation to get about the changes.

**Comment by dscheg** [comment]
Isn't it inconsistent that with the position of the legend on the right, the legend seems to be taken into account?
```js
var chart = bb.generate({
  padding: {right: 1},
  legend: {position: 'right'},
  data: {
    columns: [
	["data1", 300, 350, 300, 0, 0, 0],
	["data2", 130, 100, 140, 200, 150, 50]
    ],
    types: {
      data1: "area",
      data2: "area-spline",
    }
  },
  bindto: "#areaChart"
});
```
![image](https://github.com/naver/billboard.js/assets/1962268/375991b7-edf6-4a51-a59c-615d8d96a6c3)

**Comment by netil** [comment]
@dscheg you're right. it should be excluded also.
I'll be looking it to fix that.

**Comment by dscheg** [comment]
Ok, thx for clarification

**Comment by netil** [comment]
> you're right. it should be excluded also.

@dscheg Let me correct this, the current applying on padding is correct.
I wasn't thinking about the axis area, which your example doesn't included. That was my mistake leaving comment without countint it.

if you have checked the doc, you can see that padding starting point is from the shape(which is red colored background area).
![image](https://github.com/naver/billboard.js/assets/2178435/3fec266a-56a2-4b2c-a97a-a75ca3c44858)

if you generate with y2 axis to be shown, will behave same as x axis.
```js
bb.generate({
  padding: {right: 1},
  legend: {position: 'right'},
  axis: {
    y2: {show: true}
  },
  data: {
    columns: [
      ["data1", 300, 350, 300, 0, 0, 0],
      ["data2", 130, 100, 140, 200, 150, 50]
    ],
    types: {
      data1: "area",
      data2: "area-spline",
    }
  }
});
```

<img width="518" alt="image" src="https://github.com/naver/billboard.js/assets/2178435/1049d486-8e14-42f9-b4b8-9f1697745460">

Similarly, when legend stays at the bottom and set x axis hidden, will behave same as y2 axis.
Legend is not overlapped, because x axis isn't showing.

```js
bb.generate({
  padding: {bottom: 1},
  axis: {
    x: {show: false}
  },
  data: {
    columns: [
      ["data1", 300, 350, 300, 0, 0, 0],
      ["data2", 130, 100, 140, 200, 150, 50]
    ],
    types: {
      data1: "area",
      data2: "area-spline",
    }
  }
});
```

<img width="525" alt="image" src="https://github.com/naver/billboard.js/assets/2178435/c4b99584-0bea-4d52-9e5f-103469343062">

Sorry for the wrong info.

**Comment by dscheg** [comment]
This seems a little counterintuitive to me. Don't really understand the connection between displaying an axis and including a legend in the calculation from the point of view of a developer using the library :) But maybe that's ok, I don't have too many real cases

**Comment by netil** [comment]
@dscheg, added more info about how we concluded the decision.
Checkout the section titled as `Inconsistency of padding on previous versions`, from the [Understanding Padding](https://github.com/naver/billboard.js/wiki/Understanding-padding) doc.
