### ISSUE TITLE
Better tooltip for ranged bar charts

### ISSUE THREAD

**Issue by filipfloden** [naver/billboard.js#3507]
## Description
I think ranged bar chart tooltip should be changed to the same way https://github.com/naver/billboard.js/issues/3495#event-10840046927 has been implemented. 
Instead of calling tooltip.format.value twice (once with start value and once with end value) it should be called once with value as an array [start, end].

**Comment by netil** [comment]
> it should be called once with value as an array [start, end].

It isn't called twice. It will be called once with array data.
When you add `console.log` on data.labels.format, it will looks like called multiple times with single number value, because it is the process where determining text length using format function. It can't avoid not calling it, because label text can be modified using it.

**Comment by bj00rn** [comment]
> > it should be called once with value as an array [start, end].
> 
> It isn't called twice. It will be called once with array data. When you add `console.log` on data.labels.format, it will looks like called multiple times with single number value, because it is the process where determining text length using format function. It can't avoid not calling it, because label text can be modified using it.

Here is the line i'm thinking about for tooltip value

https://github.com/naver/billboard.js/blob/d2923f2db88cf3d7ab868eeb44d4e6aaaaf5d87b/src/ChartInternal/internals/tooltip.ts#L203

It would be nice if valueFormatter is called with [start, end] in order to show something other than  `start ~ end`.

I would like to show the absolute value for each bar to acheive something like a waterfall chart.

#3495 solved the same issue for me for data labels

![image](https://github.com/naver/billboard.js/assets/10961167/5abe7e6a-7b80-4a2e-a134-859bbfc0dad3)

**Comment by bj00rn** [comment]
> Hmm... there was a misunderstanding here. I was pointing that not called twice for `data.labels.format` option, but you was mentioning on `tooltip.format.value` option, right?
> 
> Updating the way that worked, could derive backward compatibility issue. I'm not sure this is a bug or enhancement. I'll be considering for that. Thanks anyway.

Agree, in the case of `rangedBarChart` it makes sense to have tooltip return whatever based on [start, end], but I guess changing behaviour would/should affect other ranged chart types as well.

**Comment by netil** [comment]
well the update only affect for bar ranged type. It could affect some compatibility issue on that type, but will not for other types.
