### ISSUE TITLE
Regions are poorly rendered

### ISSUE THREAD

**Issue by Blaumaus** [naver/billboard.js#3790]
On a line chart, regions are often poorly rendered (not as a straight line):

<img width="133" alt="Screenshot 2024-05-29 at 19 35 36" src="https://github.com/naver/billboard.js/assets/35810911/aac5e83e-ce78-4e71-ad86-6dd67977489d">
<img width="513" alt="Screenshot 2024-05-29 at 19 35 54" src="https://github.com/naver/billboard.js/assets/35810911/1c934718-e03b-44e9-b5dc-5240a5952b67">

It's not a massive bug, but it catches an eye and spoils the UI a tiny bit.

There's also one more extreme example:
<img width="1439" alt="Screenshot 2024-05-29 at 19 37 41" src="https://github.com/naver/billboard.js/assets/35810911/9bdf55fa-5136-416a-b3e3-34f3e8dedb9a">

Regions seem to be much more "clunky" compared to a regular line near them.

Could you please advice, maybe there's some kind of option I missed that may fix this? Or maybe some sort of `shape-rendering: geometricprecision` may be applied on regions to render them a bit better?

Thank you for building this beautiful library.
All the best!

**Comment by netil** [comment]
Hi @Blaumaus, thanks for the cheering message. 
The apply of `regions` can make to render specific range as dashed is implemented as moving point and drawing line commands. And between these commands(and its coordinate) can possibly be overlapped, as your example.

One of the workaround or trick is rendering multiple dataseries separately, by dividing as normal and dashed.
And control dashed line with CSS style rather than path commands. It'll get more clear by checking below example.
- https://jsfiddle.net/netil/p4vjh6cu/2/
