### ISSUE TITLE
Tooltips on bar charts do not work in Firefox as of 3.12.3

### ISSUE THREAD

**Issue by m-gallesio** [naver/billboard.js#3854]
I am using **Firefox 128.0.2 on Windows 10**.
Tooltips on bar charts do not work with **billboard.js >= 3.12.3**.
They do work correctly in version 3.12.2.

This can be seen in any documentation page (e.g. https://naver.github.io/billboard.js/demo/#Chart.BarChart)

This seems to be a Firefox-specific problem, since they work in Edge 126.0.2592.113.

**Comment by netil** [comment]
@m-gallesio thanks for the report. I'll go over it.

**Comment by netil** [comment]
@m-gallesio, tested on :
- Windows 10 Pro(22H2),
- FF v128.0, v128.0.2 and 129.0b8(beta)

As you can see from the below screenshot, it works showing tooltip correctly.
![treemap-chrome](https://github.com/user-attachments/assets/4f2dfe62-5c71-45f1-97e7-9f258aa2c2a9)

From the billboard.js 3.12.3 release, updated input type(mouse or touch) determination logic which possible the cause of your case. Check if you're using touch enabled devices.

**Comment by m-gallesio** [comment]
My device is a regular laptop and should not be touch-enabled; I will have to look more into this.

**Comment by Mathnstein** [comment]
I can confirm the issue is that newer firefox and this interaction property is not being set correctly. Here is solution with touch explicitly set to false:
![explicit_touch_false](https://github.com/user-attachments/assets/f8b15eaf-e1dd-4905-9884-dfdf052287c7)

**Comment by TheWitness** [comment]
The interaction setting mentioned above worked on my Lenovo P52s laptop with a touch screen.

**Comment by grassick** [comment]
I can confirm that this also occurs in Chrome on certain devices with Billboard 3.13.0.

**Comment by netil** [comment]
Thanks all who shared the status. 

> media queries WITH parentheses

@m-gallesio, yeah there's a omission of parentheses.
```js
matchMedia.("any-pointer:fine") 
matchMedia.("(any-pointer:fine)") // <-- to-be
```
Aside of the omission of media query detection, the criteria to select what input type get priority over are follows:
1) mouse
  even if possess touch screen, if has mouse input will make to interact using mouse event
2) touch
  when it doesn't possess any mouse device

So, base on the above criteria, internally use feature detection, and to filter cases with "mouse + touchscreen" used `any-pointer:fine` and `any-hover:hover`.
- https://css-tricks.com/interaction-media-features-and-their-potential-for-incorrect-assumptions/#aa-testing-the-capabilities-of-all-inputs

But doing the [real test](https://patrickhlauke.github.io/touch/pointer-hover-any-pointer-any-hover/), those 2 features returned true on Android device.

feature | Galaxy S22 (Android 13) | iPhone 15 Pro (iOS 18) | MacOS 14.6.1 (Chrome 129, FF 131) non touchscreen
--- | :---: | :---: | :---: 
pointer:none |  false | false | false
pointer:coarse | `true`  | `true` | false
pointer:fine | false | false | `true`
hover:none | false | `true` | false
hover:hover | `true` | false | `true`
any-pointer:none | false  | false | false
any-pointer:coarse | `true` | `true` | false
**any-pointer:fine** | `true` | false | `true`
any-hover:none | false | `true` | false
**any-hover:hover** | `true` | false | `true`

Since not having any touch capable screen + desktop environment,
@Mathnstein @m-gallesio, could you share what gives the result from below page?
- https://patrickhlauke.github.io/touch/pointer-hover-any-pointer-any-hover/

**Comment by Mathnstein** [comment]
@netil here is my results for a Dell Precision 5550 on FF 131.0.2 (64-bit)
![grafik](https://github.com/user-attachments/assets/05a58c26-ddb4-4c09-bed2-d7a5c1c6a691)

Note: You can use the devtools to emulate other envs - 
![grafik](https://github.com/user-attachments/assets/254f0305-2f6b-4e7f-b540-ca4b5cbb9131)

**Comment by netil** [comment]
@Mathnstein thanks for sharing.

Obviously every browser has emulation mode for basic tests, but those emulation in many cases doesn't reflect or provide the result from real devices. For edge cases, it needs real tests results to figure out the solution.

**Comment by m-gallesio** [comment]
HP ZBook 15 G6 Mobile Workstation
Firefox 131.0.2 (64 bit) on Windows 10 Pro 19045.4894
Edge 129.0.2792.79 (64 bit)

Same result on both browsers:
![immagine](https://github.com/user-attachments/assets/7fb207fc-3f04-4e41-ba9d-f16b5523b0f3)

**Comment by netil** [comment]
So, from the collected data, feature to detect touch devices are:
- pointer:coarse: true
- pointer:fine: false

I'll be using above data to fix the issue. Thanks all for the contribution!

**Comment by m-gallesio** [comment]
I can confirm it works.

As a further test, I tried connecting a [Wacom touch display (DTH-1152)](https://www.wacom.com/it-it/products/dth-1152) which changes the table as such:
![immagine](https://github.com/user-attachments/assets/e07cb321-4503-4273-9e94-747a3a7a9c78)

It works both with and without the tablet connected.
