### ISSUE TITLE
Grouped stacked bar charts

### ISSUE THREAD

**Issue by flipcode1973** [naver/billboard.js#392]
Is it possible to have grouped and stacked bar charts? Something like the following...

![image](https://user-images.githubusercontent.com/38728488/39369118-5998e6d8-4a33-11e8-8eec-c86683f27dc0.png)

I'm pulling the data in from the a CSV (columns something like)
Month,Net,NetRemain,Budget,BudgetRemain
Feb-2017,90,10,85,10 
etc...

The bar would be Net with NetRemain stacked, next to it for the same month would be Budget and BudgetRemain stacked. Is this possible?

Thanks.

**Comment by netil** [comment]
Hi @flipcode1973. It's possible show stacked bars.
I made a simple demo to checkout, but maybe you need to re-organize data binding to do so.

- https://jsbin.com/fobogah/edit?html,js,output
![image](https://user-images.githubusercontent.com/2178435/39415362-3c5fbd70-4c7d-11e8-8bba-51aba5518af5.png)

```js
bb.generate({
		data: {
			x: "x",
			columns: [
				["x", "2013-01-01", "2013-01-02", "2013-01-03", "2013-01-04", "2013-01-05", "2013-01-06"],
				["data1", 20, 50, 100, 50, 50, 50],
				["data2", 50, 90, 110, 80, 22, 74],
				["data3", 100, 20, 90, 70, 52, 44],
				["data4", 90, 50, 70, 55, 75, 65],
			],
            type: "bar",
            groups: [
            	["data1", "data2"],
	            ["data3", "data4"]
            ]
```

**Comment by flipcode1973** [comment]
Fantastic, works a treat. Thank you!

**Comment by michaelreynolds** [comment]
Is it possible to show a stacked area instead of stacked bars? The demo shows what should be stacked area, but it's really just a filled overlapping line chart. 

This page says there's a [stacked area chart](https://naver.github.io/billboard.js/demo/#Chart.StackedAreaChart) but it show an `area-spline` instead and is not stacked or additive. Is this a typo or incorrectly labeled?

https://naver.github.io/billboard.js/demo/#Chart.StackedBarChart
