### ISSUE TITLE
'scaleOrdinal' property undefined in the billboard.js file on the website's homepage

### ISSUE THREAD

**Issue by kyle-hall** [naver/billboard.js#4]
## Description

While trying the 'getting started' example on the homepage for this library, I keep getting the following error: 'Uncaught TypeError: Cannot read property 'scaleOrdinal' of undefined' and the line it complains about in the un-minified version is line 5279, in the ChartInternal.generateColor function. I am using the billboard.js and billboard.css linked on the homepage, which are placed at the root of the same directory where I have my HTML file. I see this in Chrome and Firefox on Windows 7.

## Steps to check or reproduce

My billboardTest.html:

```
<!DOCTYPE html>
<html>
    <head>
        <title>Billboard.js Test</title>
        <script defer src="https://d3js.org/d3.v4.min.js"></script>
        <script src="billboard.js"></script>
        <link rel="stylesheet" href="billboard.css">
    </head>

    <body>
        <div id="chart"></div>

        <script>
            var chart = bb.generate({
                bindto: '#chart',
                data: {
                    type: 'bar',
                    columns: [
                        ["data1", 30, 200, 100, 400, 150, 250],
                        ["data2", 130, 100, 140, 200, 150, 50]
                    ]
                }
            });

        </script>
    </body>
</html>
```

**Comment by netil** [comment]
@kyle-hall the error occurs, because of the `defer` property you set loading d3.js.

In the below link you can see the differences how script are loaded, parsed and executed.
- http://www.growingwiththeweb.com/2014/02/async-vs-defer-attributes.html

`defer`, technically defer the execution of script to the last, which billboard.js loads normally.
billboard.js is dependent on d3.js, so to be normally executed to functioning, it needed d3.js loaded prior the billboard.js.

I don't know the reason of `defer` prop that you put, but to solve the issue there're many alternatives you can take.
- just remove `defer`
- or if you want script don't block parsing html, just move script loading at the bottom before the body close tag like
    ```html
        ...
        <script src="https://d3js.org/d3.v4.min.js"></script>
        <script src="billboard.js"></script>
    </body>
    ```

Try this online modifying the code
- https://jsbin.com/waxekec/edit?html,js,output

**Comment by kyle-hall** [comment]
Okay, I see. I thought I tested it without the defer, but obviously I didn't. I just tried it without the defer and it worked, no problems. Thanks for taking the time to explain. I'll close this issue.
