### ISSUE TITLE
how change color axis and legend??

### ISSUE THREAD

**Issue by BeomsooIn** [naver/billboard.js#448]
i wonder how change color axis and legend

**Comment by netil** [comment]
Hi @BeomsooIn, I think it should be more specific what part of element you want to change.

For example, if you want change the color of axes lines, you can set styles as :
```css
.bb-axis line, .bb-axis .domain {
  stroke: red
}
```

And you'll get red axes.
![image](https://user-images.githubusercontent.com/2178435/41504332-6b9e84a8-7226-11e8-9e3b-fb732d26834b.png)

Every chart elements has css class names defined, so you can handle using these rules.
Otherwise, let me know the exact elements to do so.
