### ISSUE TITLE
Usage with React?

### ISSUE THREAD

**Issue by stevenmusumeche** [naver/billboard.js#5]
Have you had success with using this library in a React project?

**Comment by netil** [comment]
@stevenmusumeche, well I can't say billboard.js has success experience on React(because, it has been released just few days ago), but the original libaray C3.js, which billboard.js is the forked version of that, has meaningful experiences on React.

If you do search, you can find several C3.js React bindings(ex. https://github.com/bcbcarl/react-c3js) and some technical articles(ex. http://blogkrystalraphael.azurewebsites.net/integrating-c3-with-react/), that you can take a look how worked on React.

billboard.js inherited all of the characteristics of C3, so I think will act same as the original library.
Later you can share your experience, which will be helpful to everyone.

**Comment by planttheidea** [comment]
Not sure if it helps, but i just released [`react-billboardjs`](https://www.npmjs.com/package/react-billboardjs), which takes cues from `react-c3js` but obviously makes use of `billboard.js`. I also tried to add some enhancements related to `PureComponent` usage. Usage of it is indeed the same as `react-c3js`, so migration path should be frictionless.

**Comment by netil** [comment]
Great job! @planttheidea.
I'm curating the list of third-party apps on wiki page.
- https://github.com/naver/billboard.js/wiki/Third-party-applications
