### ISSUE TITLE
Display text if chart is empty. (Question)

### ISSUE THREAD

**Issue by TinusJ** [naver/billboard.js#504]
## Description
Hi, is it possible to display text if the chart is empty ? all values have null / 0;

[Fiddle](https://codepen.io/anon/pen/vaxZQq)

Example of what i want.
![image](https://user-images.githubusercontent.com/16685359/43058098-0d1af268-8e46-11e8-9672-b7c93e5ad343.png)

**Comment by netil** [comment]
Hi @TinusJ, there's [data.empty.label.text](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.data%25E2%2580%25A4empty%25E2%2580%25A4label%25E2%2580%25A4text) option for that purpose.
But, to be used correctly, the data should be empty, rather than 0 or null.

```js
data: {
        // 1) this will show 'No Data' text
	columns: [],

        // 2) this doesn't mean data are empty. 0 is also considered as a data
	columns: [ 
            ["data1", 0, 0, 0, 0, 0, 0]
        ]
```

The definition of `empty` will be differing depending on your definition. The default behavior on billboard.js is having `no data`.

IMO, there're two ways to fulfill your needs.
- (1) Make your data `empty` when is empty.
- (2) If you can't doing (1) option, just force to display empty text manually

Checkout the working example I made:
- https://jsbin.com/xejavow/edit?html,js,output

**Comment by TinusJ** [comment]
Thanks, will implement the second.
