### ISSUE TITLE
Using custom pattern point does not work/show in export

### ISSUE THREAD

**Issue by TinusJ** [naver/billboard.js#541]
## Description
Issue : using custom svg points / paths does not work / show when the chart is exported.
![image](https://user-images.githubusercontent.com/16685359/44136808-7ca574ca-a06e-11e8-8096-d1d6acec34f6.png)

## Steps to check or reproduce
i have added a https://codepen.io/anon/pen/ejagzB

**Comment by netil** [comment]
Hi @TinusJ, the issue is reproducible, but isn't quite easy to be solved.

The export is done by serializing SVG node elements, then coverted to dataURI format.

I'm not sure if there're limitation from the browser to not handling all the SVG nodes or some other reasons on treating that well.

It will take some time on figuring out(or solve) the issue.

**Comment by TinusJ** [comment]
@netil  any news on this?

**Comment by netil** [comment]
@teichmaj, sorry for the delays.
I couldn't digging yet. I'll try check if this can be solved(or some workaround) soon.

**Comment by jeroen-hoekstra** [comment]
@netil. I think we have a related issue. We are using FontAwesome icons in our graphs, similar to the example on [this page](https://naver.github.io/billboard.js/demo/#Point.CustomPointsFontIcon). These icons are also not visible after exporting the graph. Can we somehow work around this issue?

**Comment by netil** [comment]
@jeroen-hoekstra I'll dig into.
