### ISSUE TITLE
When a min / max is specified, spread ticks evenly across whole chart

### ISSUE THREAD

**Issue by neil-morrison44** [naver/billboard.js#7]
## Description
The ticks remain locked to the data points, rather than nicely spreading out to the full range.
I have an application that needs to show the same timeseries range and often there will be gaps in the data shown.
I'd like if Billboard could know to spread the ticks out nicely when the range of the chart exceeds the range of the data.

## Steps to check or reproduce
https://jsfiddle.net/sc1sn35u/
https://jsfiddle.net/tz646yhu/1/

**Comment by netil** [comment]
@neil-morrison44 thanks for your suggestion.

In this case manipulating option depend the data binding will be more adequate.
Just seeing how chart is rendered, is obvious your opinion, but in other perspective, it can be correct how it is rendered as now, because max value is set.

I'll take in consideration for the next release how to implement this to be more "nicer".
