### ISSUE TITLE
Intent to ship export as an image method.

### ISSUE THREAD

**Issue by netil** [naver/billboard.js#78]
## Description

Implement new method to export as an image.

```js
// interface
chart.export(MIMEType);

// ex. Export chart as png image
chart.export("image/png");
```

**Comment by julien** [comment]
Hi @netil,

Would you like this to be implement directly in billboard.js or would you be ok to use a dependency such as [dom-to-image](https://github.com/tsayen/dom-to-image)?

**Comment by julien** [comment]
Hi,

I have two proposals for this feature and also some questions.

I haven't submitted the pull request **yet**, because I'd like to clarify some points; but seeing the code might help us decide which of the two solutions is the best for billboard.js

You can see the code changes here:

- [Export using a dependency](https://github.com/julien/billboard.js/tree/export-image-with-deps)

- [Export using no dependency](https://github.com/julien/billboard.js/tree/export-image-no-deps)

### Questions

- Should we use a dependency to implement this feature?

  Each solution has it's **pros** and **cons**, but exporting `svg` (to `canvas`) to `image` can 
  be tricky. The [dependency](https://github.com/tsayen/dom-to-image) used seems to work well across major browsers, and it would avoid 
  having to write and maintain code that is not really related to charts. *(This is just my 
  opinion)*. You'll also notice that the solution with no dependency is very much inspired by **dom-to-image**.

- Should the image be automactially downloaded?

   Forcing the download is also something that might be problematic in some browsers, and it also might give us some trouble writing the tests (karma doesn't like page reloads)

- Does it make sense to try to export to `image/jpeg`?
  
  When implementing these "example" solutions, I noticed that when exporting to `image/jpeg` might not make sense since `svg` and `png` support transparency but `jpeg` doesn't.

- What do you think about `Promise`s?

   In my example solution (with no dependencies) I used a `callback` as the only argument to the 
  `export` function because I didn't see any use of `Promise` in the billboard.js codebase and 
  wasn't sure if I was "allowed" to use it. 

Let ne know what you think when you can.

Thanks!

**Comment by netil** [comment]
- #### Should we use a dependency to implement this feature?
  Well, the basic idea is always keep simpler, lighter minimizing the dependency.
  I prefer implement this without an external library. I don't think that is really complicated implementing this.

- #### Should the image be automactially downloaded?
  Not really. The main point is give a functionality to get as an image. Automatic is kinda helper added on it. If there's a demand we can implement this later of course.
 
- #### Does it make sense to try to export to image/jpeg?
  I think it doesn't really matter. After the download user can easily convert to other format if want. So, technically giving option with or without will be enough for this moment.

- #### What do you think about Promises?
  That's the way to go. For this moment, billboard.js supports legacy old browsers like IE9.
  Using promise need to have some [polyfill](https://github.com/taylorhakes/promise-polyfill) (or babel plugin) for that environment, but adding polyfill will increase the size(like promise-polyfill is 2.5KB).

  In near future the usage for old browsers will degrade, so automatically we can transitioning async syntax to be using Promise.

**Comment by julien** [comment]
@netil thanks for the info,

I'll clean up my code and submit a PR with no dependencies.
