### ISSUE TITLE
If there is a chart in swipe area, swipe will not work.

### ISSUE THREAD

**Issue by ddurung101** [naver/billboard.js#82]
## Description
If there is a chart in swipe area, swipe will not work.

## Steps to check or reproduce

- https://github.com/naver/billboard.js/blob/master/src/interactions/interaction.js#L109-L113

- 
![chart1](https://user-images.githubusercontent.com/19185315/28529279-19552934-70cb-11e7-8282-9a81e87319be.gif)

**Comment by VReality64** [comment]
@ddurung101 

I think it's not issue just need conversation.
Billboard have to decide what Billboard want to give.

If user swipe on chart
 - user want to swipe
 - user want to move indicator on axes like snap

**Comment by netil** [comment]
To fulfill this issue, it needs to figure out the user's intention.

The current approach was calculating the distance of touch moved (from the touchstart and touchmove) and preventing the default event(calling `.preventDefault()`) in `touchmove` event.

This approach seems to be reasonable first time, but the problem is when the event wasn't prevented from the `touchstart` and the document is started to scroll at this point, preventing event in `touchmove` become  useless.

So, to prevent document scroll it needs to prevent from the `touchstart` event. In that situation is hard to figure out the intention. If user wants to drag to check the data point of chart or just wants to scroll the document.

There's no perfect solution for this, so interim solution giving control of that behavior seems to be best for now.
```js
interaction: {
    inputType: {
        preventDefault: false  // default is 'true'
    }
```

**Comment by ddurung101** [comment]
@VReality64
I think you are right. :)
But, I think we need to consider it.

@netil 
Thank you for reviewing it.
