### ISSUE TITLE
Can I customize offset of Y axis?

### ISSUE THREAD

**Issue by JaeYeopHan** [naver/billboard.js#823]
## Description

I want to keep the interval of each step of Y axis same. At the same time keeping range of values in line chart of billboard.

### Designer's Requirements

<img width="221" alt="designer_requirements" src="https://user-images.githubusercontent.com/17924127/55378255-3ae14880-5553-11e9-94a7-9ff955471b09.png">

### Current view

![current_view](https://user-images.githubusercontent.com/17924127/55378267-43398380-5553-11e9-949f-bf0fd65ed3eb.png)

## Steps to check or reproduce

- values: `[1, 5, 10, 50, 100]`

```js
axis: {
  y: {
    min: [1, 5, 10, 50, 100][0],
    max: [1, 5, 10, 50, 100][4],
    tick: {
      values: [1, 5, 10, 50, 100],
    },
  },
},
```

**Comment by netil** [comment]
Hi @JaeYeopHan, you can do by displaying different numbers on each of y axis tick.

```js
axis: {
	y: {
		min: 0,
		max: 100,
		tick: {
			values: [0, 20, 40, 60, 80, 100],
			format: x => ({0: 0, 20: 5, 40: 10, 60: 15, 80: 50, 100: 100}[x])
		}
	}
}
```
![image](https://user-images.githubusercontent.com/2178435/55380641-c363e700-555b-11e9-8834-477fe93fb805.png)

But, as you've been noticed here, this is kinda against on visualizing data in incorrect scale.

The data are visualized according the area and they're scaled based on the amount of the space.
So, in a correct way, this is like:

![image](https://user-images.githubusercontent.com/2178435/55381220-839dff00-555d-11e9-939f-e6c6a958483e.png)

I think this is something strongly for `design` related needs, which is breaking the correct visualization.
I don't recommend approaching as this way, because simply is not `correct` way and it is letting to  misunderstand the `real` data.

**Comment by JaeYeopHan** [comment]
Thank you for quick response! Very useful suggestion. It would be best to consult with the designer and make adjustments.
