### ISSUE TITLE
Question: What is this number at the end of my xAxis ?

### ISSUE THREAD

**Issue by dark-knight96** [naver/billboard.js#842]
## Description
Hello. I am using billboard 1.8 and I have this number at the end of my xAxis referring to the number of ticks that is displayed on my xAxis. I tried disabling the external tick but it did't work. I don't know if this is a bug or configuration issue and would appreciate any help that is provided. I have attached a screenshot for reference. 

<img width="1060" alt="Screen Shot 2019-04-11 at 3 31 18 pm" src="https://user-images.githubusercontent.com/24488737/56111967-44b57380-5f77-11e9-9d1b-4605e1906ac6.png">

**Comment by netil** [comment]
Hi @dark-knight96, can you provide the generation code?

**Comment by dark-knight96** [comment]
Hello @netil , 
Thank you for the response. These are my chart parameters. 
[chart.txt](https://github.com/naver/billboard.js/files/3080315/chart.txt)

**Comment by netil** [comment]
@dark-knight96, try with the option `axis.x.tick.fit = true`.

**Comment by dark-knight96** [comment]
Hi @netil 
It worked. Thank you for your help. But may I know what caused this ?

**Comment by netil** [comment]
@dark-knight96, the basic reason is that for `category` axis type, the `tick.fit` option is useless.
There're two reasons internally why behaves as this way.

### 1) axis.x.tick.fit option
The [`axis.x.tick.fit`](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.axis%25E2%2580%25A4x%25E2%2580%25A4tick%25E2%2580%25A4fit) option behaves as:

![image](https://user-images.githubusercontent.com/2178435/56339463-57cf7a00-61e9-11e9-9548-494655880a3d.png)

- true: let draw ticks according target elements count
  > for more details, checkout: https://github.com/naver/billboard.js/blob/master/src/axis/Axis.js#L599
- false: let draw all ticks according its scale

### 2) The 'category' axis type
And for category axis type, internally it customizes the domain value adding + 1 value, to customize tick's rendering space.
> for more details, checkout: https://github.com/naver/billboard.js/blob/master/src/internals/scale.js#L79

### As a result
Because of the two above reasons, when set `axis.x.tick.fit=false`, it tries draw every ticks (added + 1 for the 'category' type), with one more additional value at the end.

Is kinda of option collision here, but I think is not really critical.
