### ISSUE TITLE
Remove stroke css property from bar

### ISSUE THREAD

**Issue by netil** [naver/billboard.js#872]
## Description

`stroke` property is set to bars path elements, but this limits styling different border color via css.
To give more flexibility, make not to set inline `stroke` css property on bar path element.

**Comment by dorian-ferrer** [comment]
Hello, is there a way to still keep the stroke css the same as the fill css?

I would like to configure something like this:
```
const chart = bb.generate({
    ...
    color: {
        pattern: ['#FF0000', '#00FF00', ...],
        colorStroke: true
    }
    ...
});
```

so that my bars in the chart have different colored strokes like:
![Screen Shot 2022-07-29 at 10 18 08](https://user-images.githubusercontent.com/77304234/181803575-090771dc-c708-4593-9cdf-db249dde7e9e.png)

instead of having a single color for the stroke like:
![Screen Shot 2022-07-29 at 10 19 38](https://user-images.githubusercontent.com/77304234/181803578-9af0a5d3-99e1-4995-a6c5-a709fae45cca.png)

**Comment by netil** [comment]
Hi @dorian-ferrer, try using [`onafterinit`](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.onafterinit) option.

```js
  onafterinit: function() {
    this.$.bar.bars      
      .style("stroke-width", "1px")
      .style("stroke", "#000")
      // if want bar's stroke to have same color as data color,
      // replace above with below
      // .style("stroke", d => this.color(d))
  },
```
