### ISSUE TITLE
Issue with axis.y.padding.bottom in area/area-spline chart

### ISSUE THREAD

**Issue by sqal** [naver/billboard.js#89]
## Description
Hi. I would like to report a bug with setting bottom padding for area/area-spline chart. Please look at the reproduction example. You can see that when type chart is set to area or area-spline then `axis.y.padding.bottom` has absolutely no effect. It works when you change chart type to e.g. `line`. My problem is that i would like to use area-spline type in my chart but the chart's data may contain empty values (like in the example) so the points where the value is equal 0 are cut off by the x axis line and it doesn't look so good. So I guess the question is - Is there currently a way to fix this problem, some options in the api i have missed or is it a bug that need to be fixed first? Thanks for the help :)

## Steps to check or reproduce
https://jsfiddle.net/qfcw41oe/

**Comment by netil** [comment]
Hi @sqal. That isn't a bug.

To understand why this happens, you need to understand the way how `area` type is rendered.
Like `area` and `bar` types, it is aligned to visualize from the bottom, because the nature of those types are like that way. The bar type will be more easier to catch, because normally we think that bars are starting from the bottom to top.

I agree that giving padding also sounds reasonable, but in this case to fulfill your needs, there is a option for that purposes.

The `area.zerobased` option.
- https://naver.github.io/billboard.js/release/latest/doc/Options.html#.area

Just set `false` and you will get the result that you wanted.
```js
area: {
     zerobased: false,
}
```
![image](https://user-images.githubusercontent.com/2178435/28957817-af5287ea-792e-11e7-9191-3e0387b56b55.png)

**Comment by sqal** [comment]
@netil Thank you very much for your explanation and the solution for my problem 👍 I think you can close this issue now :)
