### ISSUE TITLE
cross browser issue (IE/edge) on custom points

### ISSUE THREAD

**Issue by alwaysrejoice** [naver/billboard.js#897]
## Description
I found the expanding effect on custom points chart don't work on IE/Edge.
you can check https://naver.github.io/billboard.js/demo/#Point.CombinationPoints on IE/Edge and compare with Chrome

Chrome has that expanding effect, but IE not, can that be fixed?

**Comment by netil** [comment]
Hi @alwaysrejoice, the latest release(1.8.1) works well on Edge(not the chromium based), but not for old IEs.

This is due to `transform` css prop set as part of style attribute, which IE don't recognize these values.
This will be fixed to be applied as `transform` attribute.
```html
<!-- as is -->
<use xlink:href="#bb-1558679906830-point-data2"  ...  style="transform:scale(1.5)"></use>

<!-- to be -->
<use xlink:href="#bb-1558679906830-point-data2"  ...  transform="scale(1.5)"></use>
```

Here is the working screenshot emulating IE9 from IE11.
![ie9-custom-point-expansion](https://user-images.githubusercontent.com/2178435/58307516-da2b0980-7e39-11e9-8a98-59670088a50e.gif)
