### ISSUE TITLE
[Question] chart is not fit in container div 

### ISSUE THREAD

**Issue by SoYoung210** [naver/billboard.js#993]
## Description

chart width is not fit in container div. (load mobile first)

but when i load in desktop size first, it works. 
![billboard2](https://user-images.githubusercontent.com/18658235/61775769-825a5000-ae34-11e9-9832-ab3150c3d139.gif)

## Steps to check or reproduce

- load chart via mobile version. 
<img width="164" alt="스크린샷 2019-07-24 오후 4 57 31" src="https://user-images.githubusercontent.com/18658235/61775687-59d25600-ae34-11e9-8969-f57e122e7e47.png">

- load chart desktop version first, and resize to mobile version 
<img width="174" alt="스크린샷 2019-07-24 오후 4 58 03" src="https://user-images.githubusercontent.com/18658235/61775729-6fe01680-ae34-11e9-88d0-55bac9828f9d.png">

Do i miss something..?

**Comment by netil** [comment]
@SoYoung210, the chart size is based on the bind element's computed(via `.getBoundingClientRect()`) size.
- https://github.com/naver/billboard.js/blob/master/src/internals/size.js#L135


If you can define chart size explicitly, might help on this.
Otherwise, if you continuously having issue on solving this, plz share some reproducible online code.

**Comment by SoYoung210** [comment]
Chart size doesn't fit well, so i'll be ready to reproduce it with codepen. Thank you for do not closing this issue. :)

**Comment by SoYoung210** [comment]
[code pen](https://codepen.io/soyoung210/pen/BXYrjE)
Here's my reproduce code. 

Chart area is little bit smaller than container's size. 

*chart*
![image](https://user-images.githubusercontent.com/18658235/62595748-86996980-b91a-11e9-8fce-19374a15ae63.png)

*container*
![image](https://user-images.githubusercontent.com/18658235/62595824-cceec880-b91a-11e9-9dfa-50ae6d6c59e0.png)

I thought this might be due to padding right 0.4, but removing the property would cut the line point.


I would appreciate it if you could help me how to solve this problem.. 🙏

**Comment by netil** [comment]
There're too many stuff around here.

1. The codepen's billboard.js looks to be `1.0.1`. Make sure to use the latest to avoid some unexpected behavior.

2. The `translate` property applied to the main element.
Because of the transform property set, make chart element to be positioned in different area.
```css
#chart > svg > g {
   -webkit-transform: translate(50px, 4.5px);
            transform: translate(50px, 4.5px);
}
```

I made an example removing that css and looks well.
- https://qkgthb.stackblitz.io
- For edit: https://stackblitz.com/edit/qkgthb?file=index.html

**Comment by SoYoung210** [comment]
Thank you for your input. 

I made above codepen from [billboard-playground](https://naver.github.io/billboard.js/playground/), but I see that I missed to check the version. 

Just for your information, other issue related to the root component padding is resolved by getting rid of the padding value. 

```html
    <div className="group-chart-wrapper">
      <div id="grouped-bar-chart" />
    </div>
```

```pcss
.group-chart-wrapper {
  /* padding: 0 15px; */
}
```

When the graph size calculated, it measured small because of this padding value.
I solved issue, Thanks a lot. @netil
